import { initializeApp } from 'firebase/app';
import { getFirestore, collection, writeBatch, doc, serverTimestamp, getDocs } from 'firebase/firestore';
import { getAuth, signInAnonymously } from 'firebase/auth';

const firebaseConfig = {
  apiKey: "AIzaSyClxA4i0G4ATpxLrJ3uSNmVFsS_Qs9U-Wk",
  authDomain: "daybreak-72ea7.firebaseapp.com",
  projectId: "daybreak-72ea7",
  storageBucket: "daybreak-72ea7.firebasestorage.app",
  messagingSenderId: "452098908230",
  appId: "1:452098908230:web:e8c32ae4f68893cf5baa47",
  measurementId: "G-CJB2MJKT27"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);

const CATEGORIES = {
  subject_verb_agreement: { id: 'subject_verb_agreement', badgeKo: '수일치 핵심' },
  tense_voice: { id: 'tense_voice', badgeKo: '시제 · 태' },
  verbals: { id: 'verbals', badgeKo: '준동사 핵심' },
  clauses_relatives: { id: 'clauses_relatives', badgeKo: '관계사 · 명사절' },
  connectors: { id: 'connectors', badgeKo: '접속사 vs 전치사' },
  parts_of_speech: { id: 'parts_of_speech', badgeKo: '품사 · 어휘' },
  modals_subjunctive: { id: 'modals_subjunctive', badgeKo: '가정법 · 조동사' },
  special_structures: { id: 'special_structures', badgeKo: '특수구문 · 도치' },
  verb_patterns: { id: 'verb_patterns', badgeKo: '자·타동사 콜로케이션' },
  parallel_agreement: { id: 'parallel_agreement', badgeKo: '병렬 · 상관접속' }
};

// -------------------------------------------------------------
// 160 FULL HIGH-YIELD QUESTIONS (Level 1~4 x 40 Qs)
// -------------------------------------------------------------
const FULL_160_DATA = [
  // =============================================================
  // 🟢 LEVEL 1 (40 Qs: 10 Categories x 4)
  // =============================================================
  { lvl: 1, cat: 'subject_verb_agreement', form: 1, s: "She ______ to the public library every morning before breakfast.", a: "goes", opts: ["goes", "go", "going", "gone"], t: "그녀는 매일 아침 아침 식사 전에 공공 도서관에 간다.", f: ["주어가 3인칭 단수(She)이고 현재 반복 습관이므로 goes가 정답입니다.", "3인칭 단수 주어에 동사원형은 불가합니다.", "단독 -ing는 본동사 불가입니다.", "have 없이 과거분사 단독은 동사 불가입니다."], cp: "3인칭 단수 주어(She) + 단수동사(goes)", nu: "매일 반복되는 일상을 나타내는 3인칭 단수 현재 시제" },
  { lvl: 1, cat: 'subject_verb_agreement', form: 2, s: "The new students in our classroom ______ very excited about the trip.", a: "are", opts: ["are", "is", "was", "be"], t: "우리 교실의 새로운 학생들은 여행에 대해 매우 신나 있다.", f: ["핵심 주어가 복수명사(The new students)이므로 복수 be동사 are가 정답입니다.", "복수 주어에 is는 수일치 위반입니다.", "복수 현재 상태이므로 was는 불가합니다.", "원형 be는 본동사 자리에 단독 사용 불가합니다."], cp: "복수 주어(The new students) + are", nu: "주어 뒤 전치사구 수식어를 걷어내고 복수 주어와 일치" },
  { lvl: 1, cat: 'subject_verb_agreement', form: 3, s: "Every teacher in this building ______ a digital tablet for class.", a: "has", opts: ["has", "have", "having", "are having"], t: "이 건물의 모든 선생님은 수업을 위한 디지털 태블릿을 가지고 있다.", f: ["Every + 단수명사는 단수 취급하므로 단수동사 has가 정답입니다.", "Every가 이끄는 단수 주어에 have는 불가합니다.", "단독 -ing는 동사 불가입니다.", "소유 의미는 진행형 불가입니다."], cp: "Every + 단수명사(teacher) + 단수동사(has)", nu: "Every 뒤 단수명사는 단수동사와 호응하는 기본 원칙" },
  { lvl: 1, cat: 'subject_verb_agreement', form: 4, s: "My elder brother often ______ me delicious snacks after school.", a: "buys", opts: ["buys", "buy", "buying", "bought yesterday"], t: "우리 형은 방과 후에 종종 나에게 맛있는 간식을 사준다.", f: ["주어(My elder brother)가 3인칭 단수이므로 단수동사 buys가 옵니다.", "3인칭 단수에 원형 buy는 수일치 위반입니다.", "단독 -ing는 동사 불가입니다.", "문맥에 맞지 않는 부사구입니다."], cp: "3인칭 단수 주어 + buys + IO(me) + DO(snacks)", nu: "수여동사의 3인칭 단수 현재 수일치" },

  { lvl: 1, cat: 'tense_voice', form: 3, s: "My uncle ______ a brand new bicycle for my birthday yesterday.", a: "bought", opts: ["bought", "buys", "buying", "will buy"], t: "삼촌은 어제 내 생일을 위해 새 자전거를 사주셨다.", f: ["명백한 과거 시점 부사인 yesterday가 있으므로 과거시제 bought가 정답입니다.", "yesterday와 현재시제는 호응하지 않습니다.", "단독 -ing는 본동사 불가입니다.", "과거 단서와 미래시제는 모순입니다."], cp: "주어 + 과거동사(bought) + 목적어 + yesterday", nu: "명백한 과거 단서 부사와 단순 과거 시제의 결합" },
  { lvl: 1, cat: 'tense_voice', form: 3, s: "This famous storybook ______ by millions of children around the world.", a: "is read", opts: ["is read", "reads", "is reading", "readed"], t: "이 유명한 동화책은 전 세계 수백만 명의 어린이들에 의해 읽힌다.", f: ["책은 읽혀지는 대상(수동)이므로 수동태 be p.p. 형태인 is read가 정답입니다.", "능동태로 쓰면 책이 스스로 무언가를 읽는다는 비문이 됩니다.", "진행형은 어색합니다.", "read의 과거분사는 read입니다."], cp: "사물 주어 + 수동태(is read) + by 행위자", nu: "사물 주어와 행위자(by)가 나타내는 기본 수동태" },
  { lvl: 1, cat: 'tense_voice', form: 1, s: "The international flight will ______ at Incheon Airport tomorrow morning.", a: "arrive", opts: ["arrive", "arrived", "arrives", "arriving"], t: "국제선 비행기는 내일 아침 인천공항에 도착할 것이다.", f: ["조동사 will 뒤에는 반드시 동사원형이 와야 하므로 arrive가 정답입니다.", "조동사 뒤 과거형 불가입니다.", "조동사 뒤 3인칭 단수형 불가입니다.", "조동사 뒤 단독 -ing 불가입니다."], cp: "조동사(will) + 동사원형(arrive)", nu: "미래를 나타내는 조동사 will + 동사원형의 기본 어순" },
  { lvl: 1, cat: 'tense_voice', form: 3, s: "The golden trophy ______ to the best singer at the ceremony last night.", a: "was given", opts: ["was given", "gave", "is given", "giving"], t: "그 황금 트로피는 어젯밤 시상식에서 최고의 가수에게 수여되었다.", f: ["트로피는 수여되는 대상이며 last night 과거 시점이므로 was given이 정답입니다.", "능동 gave는 비문입니다.", "과거 시점 부사와 현재시제는 맞지 않습니다.", "단독 -ing는 동사 불가입니다."], cp: "사물 주어 + was given + last night", nu: "과거 특정 시점에 일어난 사물 수여의 수동태" },

  { lvl: 1, cat: 'verbals', form: 3, s: "My sister decided ______ Japanese before traveling to Tokyo next summer.", a: "to learn", opts: ["to learn", "learning", "learn", "learned"], t: "내 여동생은 내년 여름 도쿄로 여행 가기 전에 일본어를 배우기로 결심했다.", f: ["decide는 미래지향적 의미의 to부정사를 목적어로 취하므로 to learn이 정답입니다.", "decide는 동명사를 취하지 않습니다.", "목적어 자리에 동사원형 불가입니다.", "과거동사는 목적어 불가입니다."], cp: "decide + to-V (to부정사 목적어)", nu: "미래의 결심을 나타내는 to부정사 목적어" },
  { lvl: 1, cat: 'verbals', form: 3, s: "They really enjoy ______ computer games together on weekends.", a: "playing", opts: ["playing", "to play", "play", "played"], t: "그들은 주말마다 함께 컴퓨터 게임을 하는 것을 정말 즐긴다.", f: ["enjoy는 동명사(-ing)만을 목적어로 취하는 대표적 타동사이므로 playing이 정답입니다.", "enjoy는 to부정사를 취하지 않습니다.", "목적어 자리에 원형 불가입니다.", "과거분사는 목적어 불가입니다."], cp: "enjoy + -ing (동명사 목적어)", nu: "현재 즐기는 활동을 나타내는 동명사 목적어" },
  { lvl: 1, cat: 'verbals', form: 5, s: "My mom always tells me ______ my teeth before going to sleep.", a: "to brush", opts: ["to brush", "brushing", "brush", "brushed"], t: "엄마는 항상 나에게 자기 전에 이를 닦으라고 말씀하신다.", f: ["tell은 5형식 구문에서 목적격 보어로 to부정사를 취하므로 to brush가 정답입니다.", "동명사는 tell의 보어로 불가합니다.", "사역동사가 아니므로 원형 불가입니다.", "과거분사는 보어로 부적절합니다."], cp: "tell + O(me) + to-V (5형식 목적격 보어)", nu: "지시나 부탁을 나타내는 tell + 목적어 + to부정사" },
  { lvl: 1, cat: 'verbals', form: 2, s: "Her favorite hobby in free time is ______ delicious cookies.", a: "baking", opts: ["baking", "bake", "baked", "bakes"], t: "그녀가 여가 시간에 가장 좋아하는 취미는 맛있는 쿠키를 굽는 것이다.", f: ["주격 보어 자리에서 '~하는 것'의 의미로 동명사 baking이 정답입니다.", "be동사 뒤 보어 자리에 원형 불가입니다.", "수동 의미가 아니므로 과거분사는 부적절합니다.", "3인칭 단수 동사는 보어 불가입니다."], cp: "주어(hobby) + is + 동명사 보어(baking)", nu: "주어의 구체적 내용을 설명하는 주격 보어 동명사" },

  { lvl: 1, cat: 'clauses_relatives', form: 3, s: "I met a friendly doctor ______ helped my grandfather last week.", a: "who", opts: ["who", "which", "whose", "what"], t: "나는 지난주에 우리 할아버지를 도와주신 친절한 의사 선생님을 만났다.", f: ["선행사가 사람(doctor)이고 뒤에 주어가 빠진 주격 관계사절이므로 who가 정답입니다.", "사람 선행사에 which 불가입니다.", "whose 뒤에는 명사가 와야 합니다.", "선행사가 있으므로 what 불가입니다."], cp: "사람 선행사(doctor) + who + 동사", nu: "사람을 수식하는 가장 기본적인 주격 관계대명사" },
  { lvl: 1, cat: 'clauses_relatives', form: 3, s: "This is the interesting novel ______ won first prize in the contest.", a: "which", opts: ["which", "who", "whom", "where"], t: "이것은 그 대회에서 1등 상을 받은 흥미로운 소설이다.", f: ["선행사가 사물(novel)이고 관계사절의 주어 역할을 하므로 which가 정답입니다.", "사물 선행사에 who 불가입니다.", "목적격 whom은 사물에 불가입니다.", "where 뒤에는 완전한 절이 와야 합니다."], cp: "사물 선행사(novel) + which + 동사", nu: "사물 명사를 한정 수식하는 주격 관계대명사" },
  { lvl: 1, cat: 'clauses_relatives', form: 1, s: "This is the quiet village ______ my grandmother was born seventy years ago.", a: "where", opts: ["where", "which", "who", "what"], t: "이곳은 70년 전에 나의 할머니께서 태어나신 조용한 마을이다.", f: ["선행사가 장소(village)이고 뒤 문장이 완전한 절이므로 관계부사 where가 정답입니다.", "which 뒤에는 불완전한 절이 와야 합니다.", "장소 선행사에 who 불가입니다.", "선행사가 있으므로 what 불가입니다."], cp: "장소 선행사(village) + where + 완전한 절", nu: "장소를 나타내는 명사 뒤에서 공간적 배경을 설명하는 관계부사" },
  { lvl: 1, cat: 'clauses_relatives', form: 3, s: "I know the exact reason ______ he was absent from school yesterday.", a: "why", opts: ["why", "which", "who", "whose"], t: "나는 그가 어제 학교에 결석한 정확한 이유를 알고 있다.", f: ["선행사가 이유(the exact reason)이고 뒤 문장이 완전하므로 관계부사 why가 정답입니다.", "which 뒤에는 불완전한 절이 와야 합니다.", "이유 선행사에 who 불가입니다.", "소유격 whose는 부적절합니다."], cp: "reason + why + 완전한 절", nu: "원인과 이유를 설명하는 관계부사 why의 기본 쓰임" },

  { lvl: 1, cat: 'connectors', form: 1, s: "We could not play soccer outside ______ it was raining heavily.", a: "because", opts: ["because", "because of", "despite", "during"], t: "비가 세차게 내리고 있었기 때문에 우리는 밖에서 축구를 할 수 없었다.", f: ["뒤에 [주어(it) + 동사(was raining)] 절이 이어지므로 접속사 because가 정답입니다.", "because of는 전치사이므로 절 앞에는 불가합니다.", "despite는 전치사입니다.", "during은 기간 명사 앞에 쓰는 전치사입니다."], cp: "주절 + 이유 접속사(because) + S + V", nu: "원인/이유를 나타내는 부사절 접속사 because vs 전치사구" },
  { lvl: 1, cat: 'connectors', form: 1, s: "They decided to go hiking ______ the sudden heavy rain.", a: "despite", opts: ["despite", "although", "even though", "because"], t: "갑작스러운 폭우에도 불구하고 그들은 하이킹을 가기로 결정했다.", f: ["뒤에 명사구(the sudden heavy rain)가 오고 양보의 의미이므로 전치사 despite가 정답입니다.", "although는 접속사이므로 명사구 앞에는 불가합니다.", "even though는 접속사입니다.", "because는 의미상 반대입니다."], cp: "주절 + 양보 전치사(despite) + 명사구", nu: "접속사(although) vs 전치사(despite)의 구조적 차이" },
  { lvl: 1, cat: 'connectors', form: 1, s: "Please stay inside the classroom ______ the teacher returns.", a: "until", opts: ["until", "during", "despite", "because of"], t: "선생님께서 돌아오실 때까지 교실 안에 머물러 있으세요.", f: ["뒤에 [주어(the teacher) + 동사(returns)] 절이 오며 시점의 한계를 나타내므로 접속사 until이 정답입니다.", "during은 전치사입니다.", "양보 전치사는 문맥에 맞지 않습니다.", "because of는 전치사입니다."], cp: "명령문 + 시간 접속사(until) + S + V", nu: "특정 시점까지의 지속을 나타내는 시간 접속사" },
  { lvl: 1, cat: 'connectors', form: 3, s: "He listened to soft music ______ he was studying for the math exam.", a: "while", opts: ["while", "during", "despite", "in spite of"], t: "그는 수학 시험공부를 하는 동안 부드러운 음악을 들었다.", f: ["뒤에 [주어 + 동사(he was studying)] 절이 이어지므로 접속사 while이 정답입니다.", "during은 전치사이므로 뒤에 절이 올 수 없습니다.", "양보 전치사는 문맥에 맞지 않습니다.", "in spite of는 전치사입니다."], cp: "주절 + 동시동작 접속사(while) + S + V", nu: "두 동작이 동시에 일어남을 나타내는 접속사 while vs 전치사 during" },

  { lvl: 1, cat: 'parts_of_speech', form: 2, s: "The freshly baked bread in the morning smells very ______.", a: "delicious", opts: ["delicious", "deliciously", "deliciousness", "more deliciousness"], t: "아침에 갓 구운 빵은 매우 맛있는 냄새가 난다.", f: ["감각동사 smell 뒤의 주격 보어 자리에는 부사가 아닌 형용사 delicious가 옵니다.", "감각동사 보어 자리에 부사는 불가합니다.", "추상명사는 어색합니다.", "문법적으로 잘못된 형태입니다."], cp: "감각동사(smell) + 형용사 보어(delicious)", nu: "2형식 감각동사 뒤 주격 보어로 형용사를 취하는 기본 원리" },
  { lvl: 1, cat: 'parts_of_speech', form: 1, s: "The little boy solved the difficult puzzle ______ in ten minutes.", a: "easily", opts: ["easily", "easy", "easiness", "easier than"], t: "그 어린 소년은 10분 만에 그 어려운 퍼즐을 쉽게 풀었다.", f: ["동사 solved를 수식하는 자리이므로 부사 easily가 정답입니다.", "형용사는 동사를 수식할 수 없습니다.", "명사는 부사 자리에 불가합니다.", "비교 대상이 없으므로 비교급은 불가합니다."], cp: "동사 + 목적어 + 부사(easily)", nu: "동사의 동작 양상을 수식하는 일반 부사의 위치" },
  { lvl: 1, cat: 'parts_of_speech', form: 2, s: "All team members remained ______ during the emergency announcement.", a: "quiet", opts: ["quiet", "quietly", "quietness", "quieted"], t: "비상 안내 방송이 나오는 동안 모든 팀원들은 조용함을 유지했다.", f: ["상태유지 동사 remain 뒤 주격 보어 자리이므로 형용사 quiet가 정답입니다.", "보어 자리에 부사 quietly는 쓸 수 없습니다.", "명사는 주어와 동격이 아니므로 어색합니다.", "과거동사는 보어 자리에 불가합니다."], cp: "remain + 형용사 보어(quiet)", nu: "2형식 상태유지 동사 뒤 형용사 보어의 필수 규칙" },
  { lvl: 1, cat: 'parts_of_speech', form: 3, s: "We need to make an important ______ about our summer vacation today.", a: "decision", opts: ["decision", "decide", "decisive", "decisively"], t: "우리는 오늘 우리의 여름휴가에 대해 중요한 결정을 내려야 한다.", f: ["관사(an)와 형용사(important)의 수식을 받는 목적어 자리이므로 명사 decision이 정답입니다.", "동사는 명사 자리에 불가합니다.", "형용사는 명사 자리에 불가합니다.", "부사는 명사 자리에 올 수 없습니다."], cp: "make + an important + 명사(decision)", nu: "관사 + 형용사 + 명사로 이어지는 목적어 명사 자리" },

  { lvl: 1, cat: 'modals_subjunctive', form: 1, s: "You ______ wear a safety helmet when riding a bicycle on the street.", a: "must", opts: ["must", "can to", "ought", "having to"], t: "도로에서 자전거를 탈 때는 안전 헬멧을 반드시 착용해야 한다.", f: ["강한 의무를 나타내며 뒤에 동사원형 wear와 결합하는 조동사 must가 정답입니다.", "조동사 can 뒤에 to는 쓰지 않습니다.", "ought는 뒤에 to가 있어야 합니다.", "단독 -ing는 조동사 불가입니다."], cp: "조동사(must) + 동사원형(wear)", nu: "안전 수칙 준수를 나타내는 의무 조동사 must" },
  { lvl: 1, cat: 'modals_subjunctive', form: 3, s: "If you study hard every day, you ______ pass the entrance test easily.", a: "will", opts: ["will", "would have", "had", "are passed"], t: "매일 열심히 공부한다면, 너는 입학시험에 쉽게 합격할 것이다.", f: ["조건절 시제가 현재(study)이므로 주절에는 미래 조동사 will이 정답입니다.", "would have는 과거완료에 쓰입니다.", "단순 과거는 미래 결과와 맞지 않습니다.", "수동태 형태는 능동 목적어와 모순입니다."], cp: "If + S + 현재동사, S + will + 동사원형", nu: "실현 가능한 미래의 조건을 나타내는 단순 조건문" },
  { lvl: 1, cat: 'modals_subjunctive', form: 1, s: "Students ______ not make loud noise inside the library.", a: "should", opts: ["should", "need to", "able to", "ought"], t: "학생들은 도서관 안에서 큰 소리를 내서는 안 된다.", f: ["도덕적 의무/금지를 나타내며 not + 동사원형과 자연스럽게 연결되는 should가 정답입니다.", "need to not은 어색합니다.", "be able to에서 be가 빠져 있습니다.", "ought not to 형태로 써야 합니다."], cp: "should not + 동사원형(make)", nu: "공공장소 에티켓을 권고하는 조동사 should" },
  { lvl: 1, cat: 'modals_subjunctive', form: 3, s: "If I ______ enough money right now, I would buy that new laptop.", a: "had", opts: ["had", "have", "will have", "having"], t: "지금 내게 충분한 돈이 있다면, 그 새 노트북을 살 텐데.", f: ["주절이 would buy(가정법 과거)이므로 조건절에는 과거동사 had가 와야 합니다.", "가정법 과거 조건절에 현재시제 have는 불가합니다.", "조건절에 미래조동사 will은 쓰지 않습니다.", "단독 -ing는 동사 불가입니다."], cp: "If + S + 과거동사(had), S + would + 동사원형", nu: "현재 사실의 반대를 가정하는 기초 가정법 과거" },

  { lvl: 1, cat: 'special_structures', form: 1, s: "The more books you read, the ______ your vocabulary becomes.", a: "richer", opts: ["richer", "rich", "richest", "more richly"], t: "책을 더 많이 읽을수록, 너의 어휘력은 더 풍부해진다.", f: ["'The + 비교급 ..., the + 비교급 ...' 상관구문이므로 비교급 richer가 정답입니다.", "the 뒤에 원급 rich는 구문에 맞지 않습니다.", "최상급은 the 비교급 구문에 불가합니다.", "becomes 뒤 보어 자리에 부사는 불가합니다."], cp: "The more ..., the richer + S + V", nu: "비례적 변화를 나타내는 The 비교급 The 비교급 기초 구문" },
  { lvl: 1, cat: 'special_structures', form: 1, s: "Here ______ the school bus that we have been waiting for.", a: "comes", opts: ["comes", "come", "coming", "is coming to"], t: "우리가 기다리던 스쿨버스가 여기 온다.", f: ["장소 부사 Here가 문두에 올 때 단수 주어(the school bus)에 맞춰 도치된 단수동사 comes가 정답입니다.", "단수 주어에 복수동사 come은 수일치 위반입니다.", "단독 -ing는 동사 불가입니다.", "불필요한 전치사입니다."], cp: "Here + 동사(comes) + 단수 주어(the bus)", nu: "유도부사 Here/There 뒤 주어-동사 도치 어순" },
  { lvl: 1, cat: 'special_structures', form: 2, s: "This math question is much ______ than the previous one.", a: "easier", opts: ["easier", "easy", "easiest", "more easy"], t: "이 수학 문제는 이전 문제보다 훨씬 더 쉽다.", f: ["than이 있고 훨씬을 뜻하는 much의 수식을 받으므로 비교급 easier가 정답입니다.", "than 앞에는 원급이 올 수 없습니다.", "than 앞에는 최상급이 올 수 없습니다.", "easy의 비교급은 easier입니다."], cp: "much + 비교급(easier) + than", nu: "비교급 강조 부사(much)와 비교급 형용사의 결합" },
  { lvl: 1, cat: 'special_structures', form: 1, s: "There ______ many colorful birds singing in the garden this morning.", a: "are", opts: ["are", "is", "was", "be"], t: "오늘 아침 정원에서 많은 다채로운 새들이 지저귀고 있다.", f: ["There 뒤의 실질 주어가 복수명사(many colorful birds)이므로 복수 be동사 are가 정답입니다.", "복수 주어에 단수 is는 수일치 위반입니다.", "복수 주어에 was는 수일치 위반입니다.", "원형 be는 단독 본동사 불가입니다."], cp: "There are + 복수 주어(many birds)", nu: "There is/are 구문에서 진주어의 수에 따른 수일치" },

  { lvl: 1, cat: 'verb_patterns', form: 1, s: "The bright morning sun ______ in the east every day.", a: "rises", opts: ["rises", "raises", "rising", "is raised"], t: "밝은 아침 태양은 매일 동쪽에서 떠오른다.", f: ["태양이 스스로 떠오르는 자동사이자 3인칭 단수이므로 rises가 정답입니다.", "raise는 타동사이므로 목적어가 없는 자리에 불가합니다.", "단독 -ing는 동사 불가입니다.", "태양은 스스로 뜨는 것이지 들어 올려지는 수동이 아닙니다."], cp: "주어(sun) + 자동사(rises) + 전치사구", nu: "자동사 rise vs 타동사 raise의 명확한 구별" },
  { lvl: 1, cat: 'verb_patterns', form: 3, s: "Please ______ the heavy box on the table carefully.", a: "set", opts: ["set", "sit", "sitting", "sat"], t: "그 무거운 상자를 테이블 위에 조심스럽게 놓아주세요.", f: ["목적어(the heavy box)를 취하는 타동사이자 명령문 원형이므로 set이 정답입니다.", "sit은 자동사로 목적어를 취할 수 없습니다.", "명령문에 단독 -ing는 불가합니다.", "명령문은 동사원형이어야 합니다."], cp: "타동사(set) + 목적어(the box)", nu: "타동사 set(놓다) vs 자동사 sit(앉다)의 구별" },
  { lvl: 1, cat: 'verb_patterns', form: 3, s: "We should ______ the environmental issues in our science club meeting.", a: "discuss", opts: ["discuss", "discuss about", "discussing", "discussed about"], t: "우리는 과학 동아리 모임에서 환경 문제에 대해 토론해야 한다.", f: ["discuss는 완전타동사로 전치사 about 없이 목적어를 바로 취하므로 discuss가 정답입니다.", "discuss 뒤에 about을 붙이면 비문입니다.", "조동사 뒤에 단독 -ing는 불가합니다.", "조동사 뒤에는 동사원형이 와야 합니다."], cp: "조동사 + 타동사(discuss) + 목적어", nu: "전치사를 붙이지 않는 순수 타동사 discuss의 핵심 어법" },
  { lvl: 1, cat: 'verb_patterns', form: 1, s: "My grandfather likes to ______ down on the sofa for a short nap.", a: "lie", opts: ["lie", "lay", "laying", "laid"], t: "할아버지께서는 짧은 낮잠을 위해 소파에 눕는 것을 좋아하신다.", f: ["'눕다'라는 의미의 자동사 원형이 to 뒤에 와야 하므로 lie가 정답입니다.", "lay는 타동사 원형입니다.", "to 뒤에 -ing는 부자연스럽습니다.", "laid는 lay의 과거/과거분사형입니다."], cp: "to + 자동사(lie) + down", nu: "자동사 lie(눕다) vs 타동사 lay(놓다)의 형태 구별" },

  { lvl: 1, cat: 'parallel_agreement', form: 3, s: "She likes both reading mystery novels and ______ delicious food.", a: "cooking", opts: ["cooking", "to cook", "cook", "cooked"], t: "그녀는 추리소설을 읽는 것과 맛있는 음식을 요리하는 것 둘 다를 좋아한다.", f: ["both A and B 구문에서 A(reading)와 B는 형태가 일치해야 하므로 동명사 cooking이 정답입니다.", "reading과 to cook은 병렬 구조에 어긋납니다.", "동사원형은 reading과 병렬을 이루지 못합니다.", "과거분사는 reading과 어울리지 않습니다."], cp: "both A(reading) and B(cooking)", nu: "상관접속사 both A and B에서 동일 품사/준동사 병렬 일치" },
  { lvl: 1, cat: 'parallel_agreement', form: 3, s: "He can speak not only English but also ______ Japanese fluently.", a: "speak", opts: ["speak", "speaking", "to speak", "spoke"], t: "그는 영어뿐만 아니라 일본어도 유창하게 말할 수 있다.", f: ["not only A but also B에서 조동사 can 뒤의 동사원형 speak와 병렬을 이루므로 speak가 정답입니다.", "조동사 뒤 동사원형과 병렬이어야 하므로 -ing는 불가합니다.", "to부정사는 can 뒤에 불가합니다.", "과거형은 can과 병렬을 이룰 수 없습니다."], cp: "not only speak A but also speak B", nu: "상관접속사 not only A but also B의 완벽한 문법적 병치" },
  { lvl: 1, cat: 'parallel_agreement', form: 1, s: "You can either stay at home ______ go to the cinema with us.", a: "or", opts: ["or", "and", "nor", "but"], t: "너는 집에 머물거나 우리와 함께 영화관에 갈 수 있다.", f: ["상관접속사 either는 or와 짝을 이루므로 or가 정답입니다.", "and는 either와 호응하지 않습니다.", "nor는 neither와 호응합니다.", "but은 not과 호응합니다."], cp: "either A or B (상관접속사 호응)", nu: "양자택일을 나타내는 상관접속사 either A or B 공식" },
  { lvl: 1, cat: 'parallel_agreement', form: 1, s: "Neither Tom ______ Jerry was able to solve the math riddle.", a: "nor", opts: ["nor", "or", "and", "but"], t: "톰도 제리도 그 수학 수수께끼를 풀 수 없었다.", f: ["상관접속사 neither는 nor와 짝을 이루므로 nor가 정답입니다.", "or는 either와 짝을 이룹니다.", "and는 both와 호응합니다.", "but은 not과 호응합니다."], cp: "Neither A nor B (상관접속사 호응)", nu: "양자 부정을 나타내는 상관접속사 neither A nor B 공식" },


  // =============================================================
  // 🔵 LEVEL 2 (40 Qs: 10 Categories x 4)
  // =============================================================
  { lvl: 2, cat: 'subject_verb_agreement', form: 3, s: "A large number of foreign tourists ______ historical landmarks in Seoul every year.", a: "visit", opts: ["visit", "visits", "visiting", "is visiting"], t: "많은 외국인 관광객들이 매년 서울의 역사적 명소들을 방문한다.", f: ["'A number of + 복수명사'는 '많은 ~'라는 뜻으로 복수 취급하므로 visit이 정답입니다.", "A number of는 복수 취급하므로 3인칭 단수형 visits는 오류입니다.", "단독 -ing는 본동사 불가입니다.", "단수 be동사는 복수 주어와 맞지 않습니다."], cp: "A number of + 복수명사(tourists) + 복수동사(visit)", nu: "A number of(많은: 복수 취급) vs The number of(수의 합계: 단수 취급)의 구별" },
  { lvl: 2, cat: 'subject_verb_agreement', form: 2, s: "The total number of electric vehicles on the road ______ increasing steadily this year.", a: "is", opts: ["is", "are", "were", "being"], t: "올해 도로 위 전기차의 총 수는 꾸준히 증가하고 있다.", f: ["'The number of ~'의 핵심 주어는 The number(단수)이므로 단수 be동사 is가 정답입니다.", "The number of는 단수 취급하므로 are는 수일치 위반입니다.", "현재 진행 상태이므로 were는 불가합니다.", "being 단독은 동사가 될 수 없습니다."], cp: "The number of + 복수명사 + 단수동사(is)", nu: "The number of 구문의 핵심 주어(The number) 단수 수일치" },
  { lvl: 2, cat: 'subject_verb_agreement', form: 3, s: "Neither the manager nor the team employees ______ about the sudden policy change.", a: "were informed", opts: ["were informed", "was informed", "informs", "informing"], t: "팀장도 팀 직원들도 갑작스러운 정책 변경에 대해 통보받지 못했다.", f: ["'Neither A nor B' 구문의 동사는 B(the team employees: 복수)에 일치시키고 수동태이므로 were informed가 정답입니다.", "B가 복수명사이므로 was는 수일치 위반입니다.", "직원들이 통보받는 대상(수동)이므로 능동형은 어색합니다.", "단독 -ing는 동사 불가입니다."], cp: "Neither A nor B(복수) + were informed", nu: "상관접속사 Neither A nor B의 근자일치(B에 수일치) 원칙" },
  { lvl: 2, cat: 'subject_verb_agreement', form: 2, s: "The quality of these manufactured components ______ proven to be outstanding.", a: "has been", opts: ["has been", "have been", "are", "having been"], t: "이 제조된 부품들의 품질은 매우 뛰어난 것으로 입증되었다.", f: ["핵심 주어가 단수명사(The quality)이므로 전치사구 수식어를 제외하고 단수 has been이 정답입니다.", "components에 낚이지 말고 핵심 주어 The quality(단수)에 맞춰야 하므로 have는 불가합니다.", "현재완료 수동태 자리에 are proven은 시제 어색합니다.", "단독 -ing는 본동사 불가입니다."], cp: "The quality(단수) + of components + has been", nu: "복수 수식어 거품 속에서 진주어의 단수성을 파악하는 수일치" },

  { lvl: 2, cat: 'tense_voice', form: 3, s: "The innovative software ______ by our development team since last December.", a: "has been updated", opts: ["has been updated", "is updating", "updated", "will update"], t: "그 혁신적인 소프트웨어는 지난 12월 이래로 우리 개발팀에 의해 업데이트되어 왔다.", f: ["'since + 과거시점' 단서와 수동 관계(소프트웨어는 업데이트됨)이므로 현재완료 수동태 has been updated가 정답입니다.", "소프트웨어가 능동으로 업데이트하는 진행형은 비문입니다.", "since와 단순 과거형은 어울리지 않습니다.", "since와 미래시제는 모순입니다."], cp: "현재완료 수동태(has been updated) + since 과거시점", nu: "과거부터 현재까지 지속된 수동의 행위를 나타내는 현재완료 수동태" },
  { lvl: 2, cat: 'tense_voice', form: 3, s: "All confidential financial records ______ in a fireproof safe before the audit began.", a: "had been stored", opts: ["had been stored", "have stored", "store", "will be stored"], t: "모든 기밀 금융 기록은 감사가 시작되기 전에 내화 금고에 보관되어 있었다.", f: ["감사가 시작된 과거(began)보다 더 이전에 보관된 수동 관계이므로 과거완료 수동태 had been stored가 정답입니다.", "현재완료는 과거 기준 시점 이전의 대과거를 나타낼 수 없습니다.", "기록이 스스로 보관하는 능동형은 불가합니다.", "과거 이전 사건에 미래시제는 불가합니다."], cp: "과거완료 수동태(had been stored) + before 과거동사", nu: "과거 특정 시점 이전의 완료된 수동 행위를 나타내는 대과거 수동태" },
  { lvl: 2, cat: 'tense_voice', form: 3, s: "The new marketing strategy ______ by the board of directors next Monday.", a: "will be reviewed", opts: ["will be reviewed", "reviews", "has reviewed", "reviewed"], t: "새로운 마케팅 전략은 다음 주 월요일에 이사회에 의해 검토될 것이다.", f: ["next Monday 미래 시점과 수동 관계(전략은 검토됨)이므로 미래 수동태 will be reviewed가 정답입니다.", "전략이 검토하는 능동형은 비문입니다.", "미래 시점 부사와 현재완료는 모순입니다.", "미래 시점에 과거형은 불가합니다."], cp: "사물 주어 + will be reviewed + next Monday", nu: "미래 시점 단서와 사물 수동태의 결합" },
  { lvl: 2, cat: 'tense_voice', form: 4, s: "The outstanding employee ______ an unexpected bonus by the CEO yesterday.", a: "was awarded", opts: ["was awarded", "awarded", "is awarding", "awards"], t: "그 우수 직원은 어제 대표이사로부터 뜻밖의 보너스를 받았다(수여받았다).", f: ["4형식 수여동사 award의 수동태 구문으로 직원이 보너스를 받은 것이므로 was awarded가 정답입니다.", "능동 awarded를 쓰면 직원이 누구에게 보너스를 주었는지 목적어가 부족합니다.", "과거 yesterday와 현재진행은 모순입니다.", "현재시제는 어제 단서와 모순입니다."], cp: "S + was awarded + DO(bonus) + by 행위자", nu: "4형식 수여동사의 직접목적어가 남는 수동태 구문" },

  { lvl: 2, cat: 'verbals', form: 5, s: "The strict safety manager made all factory workers ______ protective helmets.", a: "wear", opts: ["wear", "to wear", "wearing", "wore"], t: "엄격한 안전 관리자는 모든 공장 노동자들에게 보호 헬멧을 착용하도록 했다.", f: ["사역동사 make는 목적어와 목적격 보어가 능동 관계일 때 동사원형을 취하므로 wear가 정답입니다.", "사역동사 make는 to부정사를 보어로 취하지 않습니다.", "일반적으로 사역동사 make 뒤에 -ing는 오지 않습니다.", "과거형 동사는 목적격 보어가 될 수 없습니다."], cp: "사역동사(make) + O(workers) + 동사원형(wear)", nu: "사역동사 make의 목적격 보어로 원형부정사를 취하는 핵심 5형식 문형" },
  { lvl: 2, cat: 'verbals', form: 5, s: "We saw the talented artist ______ a beautiful mural on the wall yesterday.", a: "painting", opts: ["painting", "to paint", "painted", "paints"], t: "우리는 어제 재능 있는 예술가가 벽에 아름다운 벽화를 그리고 있는 것을 보았다.", f: ["지각동사 see는 목적어가 동작을 진행 중일 때 목적격 보어로 현재분사(-ing)를 취하므로 painting이 정답입니다.", "지각동사는 목적격 보어로 to부정사를 절대 취하지 않습니다.", "화가가 능동적으로 그리는 중이므로 과거분사는 부적절합니다.", "3인칭 단수 동사는 보어 불가입니다."], cp: "지각동사(see) + O + -ing (동작 진행 강조)", nu: "지각동사의 목적격 보어로 생생한 진행을 강조하는 현재분사" },
  { lvl: 2, cat: 'verbals', form: 5, s: "The company policy allows employees ______ remotely two days a week.", a: "to work", opts: ["to work", "working", "work", "worked"], t: "회사 규정은 직원들이 일주일에 이틀씩 원격 근무를 하도록 허용한다.", f: ["allow는 5형식 구문에서 목적격 보어로 to부정사를 취하므로 to work가 정답입니다.", "allow는 목적격 보어로 동명사를 취하지 않습니다.", "사역동사가 아니므로 동사원형은 불가합니다.", "과거분사는 능동 관계에 부적절합니다."], cp: "allow + O(employees) + to-V (5형식 보어)", nu: "미래/허가의 의미를 담아 목적격 보어로 to부정사를 취하는 5형식 동사" },
  { lvl: 2, cat: 'verbals', form: 1, s: "______ around the city center all afternoon, we were completely exhausted.", a: "Walking", opts: ["Walking", "Walked", "Having walked to", "To walk"], t: "오후 내내 도심 주변을 걸어 다녔기 때문에, 우리는 완전히 녹초가 되었다.", f: ["주절의 주어(we)가 직접 걷는 능동 관계이므로 현재분사로 시작하는 분사구문 Walking이 정답입니다.", "우리가 걸어진 수동 관계가 아니므로 과거분사 Walked는 비문입니다.", "불필요한 전치사 결합입니다.", "to부정사는 부사절 분사구문으로 어색합니다."], cp: "능동 분사구문(Walking ...) + 주절", nu: "이유/시간을 나타내는 능동 현재분사 분사구문의 자연스러운 전환" },

  { lvl: 2, cat: 'clauses_relatives', form: 3, s: "The senior engineer showed us the complex machine ______ he had designed.", a: "which", opts: ["which", "who", "whose", "where"], t: "수석 엔지니어는 자신이 설계했던 복잡한 기계를 우리에게 보여주었다.", f: ["선행사가 사물(machine)이고 had designed의 목적어가 빠진 목적격 관계대명사이므로 which가 정답입니다.", "사물 선행사에 who는 쓸 수 없습니다.", "소유격 whose 뒤에는 명사가 이어져야 합니다.", "where 뒤에는 완전한 절이 와야 합니다."], cp: "사물 선행사(machine) + 목적격 관계대명사(which)", nu: "타동사의 목적어가 생략된 관계사절을 이끄는 목적격 관계대명사" },
  { lvl: 2, cat: 'clauses_relatives', form: 3, s: "The scientist ______ groundbreaking research was published received an award.", a: "whose", opts: ["whose", "who", "which", "whom"], t: "자신의 획기적인 연구가 출판된 그 과학자는 상을 받았다.", f: ["선행사(The scientist)와 뒤의 명사(groundbreaking research) 사이의 소유 관계를 나타내므로 whose가 정답입니다.", "who 뒤에는 주어가 비어야 하는데 명사구가 바로 이어집니다.", "사람 선행사에 which는 불가합니다.", "목적격 whom은 뒤에 명사구가 이어지는 소유격 자리에 불가합니다."], cp: "사람 선행사 + whose + 명사(research) + V", nu: "선행사와 수식받는 명사의 소유 관계를 연결하는 소유격 관계대명사" },
  { lvl: 2, cat: 'clauses_relatives', form: 1, s: "The cozy cafe ______ we discussed our project yesterday has closed down.", a: "in which", opts: ["in which", "which", "whom", "what"], t: "우리가 어제 프로젝트를 논의했던 아늑한 카페가 문을 닫았다.", f: ["선행사가 장소(cafe)이고 뒤 문장이 완전하므로 [전치사 + 관계대명사]인 in which가 정답입니다.", "which 뒤에는 불완전한 절이 와야 합니다.", "사물 선행사에 whom은 불가합니다.", "선행사가 있으므로 what은 불가합니다."], cp: "장소 선행사(cafe) + in which(=where) + 완전한 절", nu: "완전한 절을 이끌며 관계부사 where의 역할을 대신하는 [전치사 + 관계대명사]" },
  { lvl: 2, cat: 'clauses_relatives', form: 3, s: "______ he explained during the conference surprised all the attendees.", a: "What", opts: ["What", "That", "Which", "Where"], t: "그가 학회 중에 설명했던 것은 모든 참석자들을 놀라게 했다.", f: ["explained의 목적어가 비어 있는 불완전한 절을 이끌며 전체 문장의 주어 역할을 하는 관계대명사 What이 정답입니다.", "접속사 That 뒤에는 완전한 절이 와야 합니다.", "선행사가 없는 문두에 which는 불가합니다.", "Where는 부사절로 목적어가 빠진 절에 부적절합니다."], cp: "What + S + V(불완전절) + 본동사(surprised)", nu: "선행사를 포함하여 '~하는 것'의 의미로 주어절을 이끄는 명사절 what" },

  { lvl: 2, cat: 'connectors', form: 1, s: "______ the severe winter blizzard, the flight took off without significant delay.", a: "Despite", opts: ["Despite", "Although", "Even though", "Whereas"], t: "극심한 겨울 눈보라에도 불구하고, 비행기는 큰 지연 없이 이륙했다.", f: ["뒤에 명사구(the severe winter blizzard)가 이어지며 양보를 나타내므로 전치사 Despite가 정답입니다.", "Although는 접속사로 뒤에 주어+동사가 와야 합니다.", "Even though는 접속사입니다.", "Whereas는 대조를 나타내는 접속사입니다."], cp: "양보 전치사(Despite) + 명사구, 주절", nu: "접속사(Although) vs 전치사(Despite)의 구조적 판별" },
  { lvl: 2, cat: 'connectors', form: 1, s: "The outdoor festival was postponed ______ unexpected torrential rain yesterday.", a: "because of", opts: ["because of", "because", "although", "while"], t: "야외 축제는 어제 예상치 못한 폭우 때문에 연기되었다.", f: ["뒤에 명사구(unexpected torrential rain)가 이어지며 원인을 나타내므로 전치사구 because of가 정답입니다.", "because는 접속사이므로 명사구 앞에는 불가합니다.", "although는 접속사이자 양보 의미입니다.", "while은 접속사입니다."], cp: "주절 + 전치사구(because of) + 명사구", nu: "명사구 앞에서 원인을 나타내는 전치사구 because of" },
  { lvl: 2, cat: 'connectors', form: 3, s: "You can borrow this reference book ______ you return it by Friday afternoon.", a: "provided that", opts: ["provided that", "in case of", "because of", "despite"], t: "금요일 오후까지 반납한다는 조건 하에 너는 이 참고서를 빌릴 수 있다.", f: ["뒤에 [주어 + 동사] 절이 오며 '~라는 조건으로'를 나타내는 접속사 provided that이 정답입니다.", "in case of는 전치사로 절 앞에는 불가합니다.", "because of는 전치사입니다.", "despite는 전치사입니다."], cp: "주절 + 조건 접속사(provided that) + S + V", nu: "if를 대체하는 고급 조건 부사절 접속사 provided that" },
  { lvl: 2, cat: 'connectors', form: 1, s: "______ the emergency drill, all employees evacuated to the designated safe zone.", a: "During", opts: ["During", "While", "Although", "Unless"], t: "비상 훈련 동안, 모든 직원들은 지정된 안전 구역으로 대피했다.", f: ["특정 사건/행사를 나타내는 기간 명사(the emergency drill) 앞이므로 전치사 During이 정답입니다.", "While은 접속사로 명사 앞에는 불가합니다.", "양보 접속사는 문맥에 맞지 않습니다.", "조건 접속사는 부적절합니다."], cp: "전치사(During) + 특정 기간 명사", nu: "특정 기간 명사와 호응하는 전치사 During vs 접속사 While" },

  { lvl: 2, cat: 'parts_of_speech', form: 2, s: "The professor gave us very ______ instructions on how to submit the essay.", a: "specific", opts: ["specific", "specifically", "specify", "specification"], t: "교수님은 우리에게 에세이를 제출하는 방법에 대한 매우 구체적인 지침을 주셨다.", f: ["명사 instructions를 앞에서 수식하는 형용사 자리이므로 specific이 정답입니다.", "부사는 명사를 직접 수식할 수 없습니다.", "동사는 명사 수식 자리에 올 수 없습니다.", "명사 연속은 문맥상 어색합니다."], cp: "very + 형용사(specific) + 명사(instructions)", nu: "명사를 한정 수식하는 형용사의 본래 역할과 위치" },
  { lvl: 2, cat: 'parts_of_speech', form: 3, s: "The manager handled the difficult customer complaint with great ______.", a: "patience", opts: ["patience", "patient", "patiently", "impatient"], t: "팀장은 그 까다로운 고객의 불만을 대단한 인내심을 가지고 처리했다.", f: ["전치사 with와 형용사 great 뒤에 명사 자리이므로 추상명사 patience가 정답입니다.", "형용사 patient는 전치사+형용사 뒤에 불가합니다.", "부사는 전치사의 목적어가 될 수 없습니다.", "형용사는 전치사 뒤 명사 자리에 불가합니다."], cp: "with + great + 명사(patience)", nu: "전치사의 목적어 역할을 수행하는 추상명사 자리" },
  { lvl: 2, cat: 'parts_of_speech', form: 3, s: "The new software update has ______ improved our team's daily productivity.", a: "significantly", opts: ["significantly", "significant", "significance", "signify"], t: "새로운 소프트웨어 업데이트는 우리 팀의 일일 생산성을 현저하게 향상시켰다.", f: ["조동사 has와 본동사 improved 사이에 동사를 수식하는 부사 자리이므로 significantly가 정답입니다.", "형용사는 동사를 수식할 수 없습니다.", "명사는 조동사-본동사 사이에 불가합니다.", "동사는 본동사 자리에 중복 불가합니다."], cp: "has + 부사(significantly) + p.p.(improved)", nu: "조동사와 본동사 사이에 위치하여 동사를 수식하는 부사 위치" },
  { lvl: 2, cat: 'parts_of_speech', form: 2, s: "The explanation provided in the manual sounded quite ______ to the beginners.", a: "confusing", opts: ["confusing", "confused", "confuse", "confusedly"], t: "설명서에 제공된 해설은 초보자들에게 꽤 혼란스럽게 들렸다.", f: ["해설(The explanation)이 혼란을 유발하는 능동적 주체이므로 현재분사 형용사 confusing이 정답입니다.", "사람이 혼란을 느낄 때 쓰는 confused는 사물 주어에 부적절합니다.", "동사원형은 sound 뒤 보어 불가입니다.", "감각동사 뒤에 부사는 보어로 올 수 없습니다."], cp: "sound + 형용사 보어(confusing)", nu: "사물 주어가 감정을 유발할 때 사용하는 현재분사 형용사" },

  { lvl: 2, cat: 'modals_subjunctive', form: 3, s: "If I ______ you, I would consult a professional financial advisor immediately.", a: "were", opts: ["were", "was", "am", "have been"], t: "내가 너라면, 나는 즉시 전문 금융 상담사에게 자문을 구할 텐데.", f: ["현재 사실과 반대되는 가정을 나타내는 가정법 과거의 be동사는 were가 정답입니다.", "가정법 과거 공식에서 be동사는 were를 원칙으로 합니다.", "현재시제 am은 가정법 과거에 불가합니다.", "현재완료는 가정법 과거에 불가합니다."], cp: "If I were you, I would + 동사원형", nu: "상대방의 입장을 가정하여 조언할 때 쓰는 표준 가정법 과거 공식" },
  { lvl: 2, cat: 'modals_subjunctive', form: 3, s: "The senior director insisted that the emergency protocol ______ immediately.", a: "be implemented", opts: ["be implemented", "is implemented", "was implemented", "implemented"], t: "상임 이사는 비상 프로토콜이 즉시 시행되어야 한다고 강력히 주장했다.", f: ["주장/요구 동사 insist 뒤 that절에는 당위성을 나타내어 (should) + 동사원형 be implemented가 정답입니다.", "직설법 is는 당위성 that절에 불가합니다.", "주절이 과거라 해도 당위성 원형 규칙이 우선합니다.", "수동태가 아니면 프로토콜이 무엇을 시행하는지 목적어가 없어 비문입니다."], cp: "insist that S + (should) + 동사원형 be p.p.", nu: "주장/제안/요구/명령 동사 뒤 that절의 동사원형(가정법 현재) 필수 규칙" },
  { lvl: 2, cat: 'modals_subjunctive', form: 3, s: "If he had checked the weather forecast, he ______ his umbrella with him.", a: "would have taken", opts: ["would have taken", "will take", "takes", "took"], t: "만약 그가 일기예보를 확인했었더라면, 그는 우산을 챙겨갔을 텐데.", f: ["조건절이 had checked(가정법 과거완료)이므로 주절에는 [would have p.p.]인 would have taken이 정답입니다.", "단순 미래는 과거완료 조건절과 결합할 수 없습니다.", "현재시제는 어울리지 않습니다.", "단순 과거형은 과거완료 조건절과 호응하지 않습니다."], cp: "If S + had p.p., S + would have p.p.", nu: "과거 사실의 반대를 가정하여 후회를 표현하는 표준 가정법 과거완료" },
  { lvl: 2, cat: 'modals_subjunctive', form: 3, s: "The committee suggested that each applicant ______ a portfolio of previous works.", a: "submit", opts: ["submit", "submits", "submitted", "to submit"], t: "위원회는 각 지원자가 이전 작업물의 포트폴리오를 제출해야 한다고 제안했다.", f: ["제안 동사 suggest 뒤의 that절이므로 (should) 생략에 따른 동사원형 submit이 정답입니다.", "each applicant가 3인칭 단수라도 당위성 동사원형 규칙이 우선하므로 submits는 오류입니다.", "과거동사는 당위성 절에 불가합니다.", "to부정사는 that절 본동사 불가입니다."], cp: "suggest that S + (should) + 동사원형(submit)", nu: "제안 동사 뒤 that절에서 주어의 수와 무관하게 동사원형을 쓰는 문법 규칙" },

  { lvl: 2, cat: 'special_structures', form: 1, s: "Never in my life ______ such an extraordinary natural phenomenon.", a: "have I seen", opts: ["have I seen", "I have seen", "I saw", "did I saw"], t: "내 평생 동안 이토록 놀라운 자연현상을 본 적은 결코 없다.", f: ["부정어 Never가 문두에 강조되어 [조동사/have + 주어 + 본동사] 순으로 도치되므로 have I seen이 정답입니다.", "평서문 어순은 부정어 문두 도치 규칙을 위반한 것입니다.", "도치가 생략된 비문입니다.", "조동사 did 뒤에 과거형 saw는 문법 오류입니다."], cp: "부정어(Never) + have + 주어(I) + p.p.(seen)", nu: "부정어 강조에 따른 주어-동사 도치 어순의 기본 원칙" },
  { lvl: 2, cat: 'special_structures', form: 1, s: "Seldom ______ the strict supervisor allow employees to leave the office early.", a: "does", opts: ["does", "is", "do", "has"], t: "그 엄격한 감독관은 직원들이 일찍 퇴근하도록 허용하는 일이 좀처럼 없다.", f: ["준부정어 Seldom이 문두에 오고 일반동사 allow를 도치시키며 단수 주어(the supervisor)이므로 조동사 does가 정답입니다.", "일반동사 원형 allow 앞에 be동사 is는 불가합니다.", "단수 주어에 do는 수일치 위반입니다.", "has는 뒤에 p.p.가 와야 하므로 원형 allow 앞에 불가합니다."], cp: "부정어(Seldom) + does + 단수주어 + 동사원형(allow)", nu: "준부정어 문두 위치에 따른 일반동사의 do/does/did 도치 구문" },
  { lvl: 2, cat: 'special_structures', form: 2, s: "The air pollution in this industrial city is much worse than ______ of the rural town.", a: "that", opts: ["that", "those", "this", "it"], t: "이 산업 도시의 대기 오염은 시골 마을의 대기 오염보다 훨씬 더 심각하다.", f: ["비교 대상인 불가산 단수명사(The air pollution)를 대신 가리키므로 대명사 that이 정답입니다.", "those는 복수명사를 대신할 때 씁니다.", "후치 수식어(of...)를 동반하는 비교 대명사는 this를 쓰지 않습니다.", "it은 한정 수식어구(of...)의 수식을 받지 못합니다."], cp: "단수 비교 대상(The pollution) ➔ that of ...", nu: "비교 구문에서 명사의 중복을 피하기 위해 사용하는 대명사 that of vs those of" },
  { lvl: 2, cat: 'special_structures', form: 1, s: "Only after completing the security training ______ granted access to the server room.", a: "were the engineers", opts: ["were the engineers", "the engineers were", "the engineers had", "did the engineers"], t: "보안 교육을 완료한 후에야 비로소 엔지니어들은 서버실 출입을 허가받았다.", f: ["'Only + 부사구'가 문두에 올 때 주절이 도치되며 수동태(be granted)이므로 were the engineers가 정답입니다.", "평서문 어순은 Only 부사구 도치 규칙 위반입니다.", "수동태가 아니므로 어색합니다.", "did 뒤에는 동사원형이 와야 하므로 과거분사 granted 앞에 불가합니다."], cp: "Only + 부사구 + were + 주어 + p.p.(granted)", nu: "Only 한정 부사구가 문두에 올 때 발생하는 주어-조동사 도치" },

  { lvl: 2, cat: 'verb_patterns', form: 3, s: "The international committee strongly ______ to the proposed ocean dumping plan.", a: "objected", opts: ["objected", "objected with", "opposed to", "disapproved about"], t: "국제 위원회는 제안된 해양 투기 계획에 강력하게 반대했다.", f: ["object는 자동사로 전치사 to와 결합하여 object to(~에 반대하다)를 이루므로 objected가 정답입니다.", "object with는 잘못된 전치사 호응입니다.", "oppose는 완전타동사로 to를 붙이면 안 됩니다.", "disapprove는 of와 결합합니다."], cp: "자동사(object) + to + 목적어", nu: "전치사 to가 필수적인 자동사 object to vs 타동사 oppose" },
  { lvl: 2, cat: 'verb_patterns', form: 3, s: "Renewable energy sources now ______ over twenty percent of the nation's total electricity.", a: "account for", opts: ["account for", "account of", "account to", "account in"], t: "재생에너지원은 이제 국가 전체 전력의 20퍼센트 이상을 차지한다.", f: ["비율/수치를 '차지하다' 또는 원인을 '설명하다'를 뜻하는 동사구는 account for이므로 for가 정답입니다.", "account of는 잘못된 숙어입니다.", "account to는 잘못된 전치사 호응입니다.", "account in은 비문입니다."], cp: "account for + 비율/수치 ('~을 차지하다')", nu: "도표 및 수능/토익 비즈니스 빈출 필수 동사구 account for" },
  { lvl: 2, cat: 'verb_patterns', form: 3, s: "Please ______ from taking photographs inside the art gallery during the exhibition.", a: "refrain", opts: ["refrain", "refrain to", "prevent", "avoid from"], t: "전시 기간 동안 미술관 내부에서 사진을 촬영하는 것을 삼가해 주십시오.", f: ["'~을 삼가다/자제하다'는 자동사 refrain과 전치사 from이 결합하므로 refrain이 정답입니다.", "refrain은 to와 호응하지 않습니다.", "prevent는 prevent A from -ing 형태로 쓰입니다.", "avoid는 타동사로 from을 붙이지 않고 바로 동명사를 목적어로 취합니다."], cp: "refrain from + -ing ('~을 삼가다')", nu: "행위 자제를 나타내는 자동사 전치사 콜로케이션 refrain from" },
  { lvl: 2, cat: 'verb_patterns', form: 3, s: "The city council plans to ______ of hazardous industrial waste safely outside the urban area.", a: "dispose", opts: ["dispose", "dispose for", "discard of", "eliminate of"], t: "시의회는 도시 지역 외부에서 유해 산업 폐기물을 안전하게 처리할 계획이다.", f: ["'~을 처리하다/폐기하다'는 자동사 dispose와 전치사 of가 결합하여 dispose of를 이루므로 dispose가 정답입니다.", "dispose for는 비문입니다.", "discard는 타동사이므로 of를 붙이지 않습니다.", "eliminate는 타동사이므로 of를 붙이지 않습니다."], cp: "dispose of + 목적어 ('~을 처리하다')", nu: "자동사 + 전치사 결합 필수 표현 dispose of" },

  { lvl: 2, cat: 'parallel_agreement', form: 3, s: "The revised software is not only faster than the old version but also ______ to operate.", a: "easier", opts: ["easier", "easily", "more ease", "ease"], t: "개정된 소프트웨어는 구버전보다 더 빠를 뿐만 아니라 조작하기에도 더 쉽다.", f: ["not only A but also B에서 A(faster: 비교급 형용사)와 B는 형태가 일치해야 하므로 easier가 정답입니다.", "부사는 faster(형용사)와 병렬을 이룰 수 없습니다.", "more ease는 잘못된 형태입니다.", "명사는 형용사와 병렬 불가입니다."], cp: "not only [비교급 형용사] but also [비교급 형용사]", nu: "상관접속사 내 형용사 비교급 간의 완벽한 문법적 병치" },
  { lvl: 2, cat: 'parallel_agreement', form: 3, s: "The workshop focuses on improving communication skills and ______ effective teamwork.", a: "building", opts: ["building", "build", "to build", "built"], t: "그 워크숍은 의사소통 능력을 향상시키고 효과적인 팀워크를 구축하는 데 중점을 둔다.", f: ["전치사 on의 목적어로 동명사 improving과 and로 연결되므로 동명사 building이 정답입니다.", "원형 build는 improving과 병렬을 이루지 못합니다.", "to부정사는 전치사 뒤 동명사와 병렬 불가입니다.", "과거분사는 능동 목적어를 취하는 동명사와 병렬 불가입니다."], cp: "focus on A(-ing) and B(-ing)", nu: "전치사의 목적어로 이어지는 동명사 간의 병렬 일치" },
  { lvl: 2, cat: 'parallel_agreement', form: 1, s: "Neither the team leader nor the senior executives ______ willing to accept the compromise.", a: "were", opts: ["were", "was", "is", "being"], t: "팀장도 고위 임원들도 그 타협안을 수락할 의사가 없었다.", f: ["'Neither A nor B' 구문의 수는 B(the senior executives: 복수)에 일치시키므로 were가 정답입니다.", "B가 복수이므로 단수 was는 수일치 위반입니다.", "과거 상태이므로 is는 시제 위반입니다.", "단독 -ing는 본동사 불가입니다."], cp: "Neither A nor B(복수 주어) + were", nu: "Neither A nor B 구문에서 B의 수에 동사를 맞추는 수일치 원칙" },
  { lvl: 2, cat: 'parallel_agreement', form: 3, s: "You must choose either to accept the promotion ______ to look for another career path.", a: "or", opts: ["or", "and", "nor", "but also"], t: "너는 승진을 수락하거나 다른 진로를 찾는 것 중 하나를 선택해야 한다.", f: ["상관접속사 either는 or와 짝을 이루며 to부정사 구문끼리 대등하게 연결하므로 or가 정답입니다.", "and는 either와 호응하지 않습니다.", "nor는 neither와 호응합니다.", "but also는 not only와 짝을 이룹니다."], cp: "either to-V or to-V (상관접속사 병치)", nu: "양자택일 구문 either A or B에서 준동사 간의 대등한 형태 일치" },


  // =============================================================
  // 🟣 LEVEL 3 (40 Qs: 10 Categories x 4)
  // =============================================================
  // 1. subject_verb_agreement
  { lvl: 3, cat: 'subject_verb_agreement', form: 2, s: "The growing discrepancy between theoretical projections and observed data ______ serious concern.", a: "has raised", opts: ["has raised", "have raised", "are raising", "having raised"], t: "이론적 예측치와 관측된 데이터 사이의 커져가는 불일치는 심각한 우려를 불러일으켰다.", f: ["핵심 주어가 단수명사(The growing discrepancy)이므로 전치사구 수식어들을 걷어내고 단수 has raised가 정답입니다.", "data에 현혹되지 않고 핵심 단수 주어 discrepancy에 일치시켜야 하므로 have는 수일치 위반입니다.", "복수 be동사는 단수 주어와 호응하지 않습니다.", "단독 -ing는 본동사가 될 수 없습니다."], cp: "The discrepancy(단수) + between A and B + has raised", nu: "복잡한 복수 병렬 전치사구 수식어를 동반한 단수 주어의 수일치" },
  { lvl: 3, cat: 'subject_verb_agreement', form: 2, s: "Two-thirds of the agricultural land in this semi-arid region ______ severely degraded.", a: "has been", opts: ["has been", "have been", "are", "were"], t: "이 반건조 지역의 농경지의 3분의 2가 심각하게 황폐화되었다.", f: ["'분수 of + 명사' 구문에서 명사가 불가산 단수명사(land)이므로 단수동사 has been이 정답입니다.", "land는 불가산 단수이므로 복수 have been은 수일치 위반입니다.", "복수 are는 불가산 명사에 쓸 수 없습니다.", "복수 were는 수일치 위반입니다."], cp: "Two-thirds of + 불가산 명사(land) + has been", nu: "부분/분수 표현(fraction of) 뒤에 오는 명사의 가산/불가산 여부에 따른 수일치" },
  { lvl: 3, cat: 'subject_verb_agreement', form: 3, s: "Each of the participants who completed the advanced clinical trial ______ a certificate.", a: "receives", opts: ["receives", "receive", "receiving", "are received"], t: "고급 임상시험을 완료한 각 참가자들은 수료증을 받는다.", f: ["핵심 주어가 Each(단수)이므로 관계사절 수식어를 제외하고 단수동사 receives가 정답입니다.", "who절의 participants에 낚이지 않고 진주어 Each에 일치시켜야 하므로 receive는 오류입니다.", "단독 -ing는 본동사 불가입니다.", "참가자가 수료증을 수령하는 능동이므로 수동태는 비문입니다."], cp: "Each of the participants + who절 + receives", nu: "관계사절 내 복수명사 함정을 극복하고 주어 Each에 맞추는 고급 수일치" },
  { lvl: 3, cat: 'subject_verb_agreement', form: 2, s: "What the researchers discovered through the longitudinal study ______ completely unexpected.", a: "was", opts: ["was", "were", "are", "being"], t: "연구진이 종단 연구를 통해 발견했던 것은 완전히 예상 밖의 일이었다.", f: ["What이 이끄는 명사절 주어는 단일 사건/개념을 나타내어 단수 취급하므로 was가 정답입니다.", "명사절 주어에 복수 were는 수일치 위반입니다.", "과거 연구 결과이므로 현재 복수 are는 불가합니다.", "being 단독은 동사 불가입니다."], cp: "What절 명사절 주어(단수 취급) + was", nu: "관계대명사 what이 이끄는 명사절 주어의 단수 취급 원칙" },

  // 2. tense_voice
  { lvl: 3, cat: 'tense_voice', form: 3, s: "By the time the new regulations take effect next month, the enterprise ______ its restructuring.", a: "will have completed", opts: ["will have completed", "completed", "has completed", "completes"], t: "다음 달 새로운 규정이 발효될 무렵이면, 그 기업은 구조조정을 완료했을 것이다.", f: ["'By the time + 현재시제(미래 대용)' 단서가 있으므로 미래 특정 시점까지의 완료를 뜻하는 미래완료 will have completed가 정답입니다.", "미래 기준 시점에 단순 과거는 모순입니다.", "현재완료는 미래 완료 시점에 부적절합니다.", "단순 현재는 특정 시점 이전의 완료를 나타낼 수 없습니다."], cp: "By the time S + 현재동사, S + will have p.p.", nu: "미래 기준 시점과 결합하여 동작의 선완료를 나타내는 미래완료 시제 공식" },
  { lvl: 3, cat: 'tense_voice', form: 3, s: "The historical manuscript ______ to have been written by a medieval scholar in the 14th century.", a: "is believed", opts: ["is believed", "believes", "is believing", "believed to"], t: "그 역사적 필사본은 14세기에 한 중세 학자에 의해 쓰였던 것으로 여겨진다.", f: ["필사본은 여겨지는 대상(수동)이며 현재의 일반적 통념이므로 is believed가 정답입니다.", "능동 believes는 사물 주어에 비문입니다.", "믿음/인식 동사는 진행형을 쓰지 않습니다.", "능동 과거형은 뒤의 to-V 완료 부정사와 어울리지 않습니다."], cp: "사물 주어 + is believed + to have p.p.", nu: "현재의 인식(수동태)과 과거의 사실(완료부정사)이 결합된 고급 수동 복문 구조" },
  { lvl: 3, cat: 'tense_voice', form: 3, s: "The suspect denied ______ any confidential information to foreign competitors.", a: "having leaked", opts: ["having leaked", "to leak", "leak", "have leaked"], t: "용의자는 해외 경쟁업체들에게 어떤 기밀 정보도 유출했던 적이 없다고 부인했다.", f: ["deny는 동명사를 목적어로 취하며, 부인한 시점보다 더 이전에 유출한 사실이므로 완료동명사 having leaked가 정답입니다.", "deny는 to부정사를 목적어로 취하지 않습니다.", "동사원형은 타동사의 목적어가 될 수 없습니다.", "동명사 형태가 아닌 have leaked는 불가합니다."], cp: "deny + having p.p. (완료동명사 목적어)", nu: "주절 시점보다 앞선 시제(대과거)를 나타내는 완료동명사(-ing have p.p.)" },
  { lvl: 3, cat: 'tense_voice', form: 5, s: "The board members had the preliminary financial report ______ by an external auditor.", a: "examined", opts: ["examined", "examine", "to examine", "examining"], t: "이사회 구성원들은 예비 재무 보고서가 외부 감사관에 의해 검토되도록 조치했다.", f: ["사역동사 have의 목적어(the report)와 보어가 수동 관계(보고서는 검토됨)이므로 과거분사 examined가 정답입니다.", "사역동사라도 목적어와 보어가 수동이면 동사원형을 쓸 수 없습니다.", "사역동사 have는 to부정사를 취하지 않습니다.", "보고서가 스스로 검토하는 능동 진행이 아니므로 부적절합니다."], cp: "have + O(사물) + p.p.(수동 목적격 보어)", nu: "사역동사 have의 목적어와 목적격 보어가 수동 관계일 때의 과거분사 보어 원칙" },

  // 3. verbals
  { lvl: 3, cat: 'verbals', form: 1, s: "______ all necessary preparation in advance, the surgical team entered the operating room.", a: "Having finished", opts: ["Having finished", "Finishing", "Finished", "To finish"], t: "사전에 필요한 모든 준비를 마쳤기 때문에, 수술팀은 수술실로 들어갔다.", f: ["수술실에 들어간 과거(entered)보다 준비를 마친 것이 더 이전이므로 완료분사구문 Having finished가 정답입니다.", "단순분사구문 Finishing은 주절과 동시 시점이 되어 문맥상 어색합니다.", "팀이 준비된 수동이 아니므로 과거분사는 비문입니다.", "to부정사는 이유의 분사구문으로 부적절합니다."], cp: "완료분사구문(Having p.p.) + 주절", nu: "주절의 동작보다 먼저 일어난 선행 사건을 나타내는 완료분사구문" },
  { lvl: 3, cat: 'verbals', form: 1, s: "With the global economy ______ rapid fluctuations, investors are adopting defensive strategies.", a: "undergoing", opts: ["undergoing", "undergone", "undergo", "to undergo"], t: "세계 경제가 급격한 변동을 겪고 있는 상황에서, 투자자들은 방어적 전략을 채택하고 있다.", f: ["'With + 목적어 + 분사' 부대상황 구문에서 경제가 직접 겪고 있는 능동 진행이므로 현재분사 undergoing이 정답입니다.", "과거분사는 수동 의미이므로 타동사 undergo의 목적어(fluctuations)가 있는 자리에 불가합니다.", "With 분사구문에 동사원형은 불가합니다.", "미래 목적이 아니므로 to부정사는 부자연스럽습니다."], cp: "With + O(the economy) + -ing(능동 분사)", nu: "동시 상황이나 배경 원인을 나타내는 With + 명사 + 분사 독립분사구문" },
  { lvl: 3, cat: 'verbals', form: 3, s: "She regretted not ______ her mentor's sincere advice regarding the investment.", a: "having followed", opts: ["having followed", "to follow", "follow", "followed"], t: "그녀는 그 투자에 관한 멘토의 진심 어린 조언을 따르지 않았던 것을 후회했다.", f: ["regret 뒤에 과거에 행하지 않은 일을 후회할 때는 동명사(완료동명사)를 쓰므로 not having followed가 정답입니다.", "regret to-V는 '~하게 되어 유감이다'라는 미래/현재 유감 표현입니다.", "동사원형은 전치사/타동사 목적어 불가입니다.", "단독 과거분사는 목적어 불가입니다."], cp: "regret + not having p.p. (과거 행위 후회)", nu: "regret to-V(유감) vs regret -ing/having p.p.(과거 후회)의 의미 구별" },
  { lvl: 3, cat: 'verbals', form: 5, s: "The high tuition fee prevents many underprivileged students from ______ higher education.", a: "pursuing", opts: ["pursuing", "to pursue", "pursue", "pursued"], t: "비싼 등록금은 많은 소외 계층 학생들이 고등교육을 추구하는 것을 가로막는다.", f: ["'prevent A from -ing' 구문에서 전치사 from의 목적어로 동명사 pursuing이 정답입니다.", "prevent 구문에서 from 뒤에 to부정사는 절대 불가합니다.", "전치사 뒤에 동사원형은 불가합니다.", "전치사 뒤에 과거분사는 부적절합니다."], cp: "prevent + O + from -ing ('A가 ~하는 것을 막다')", nu: "금지/방해 동사(prevent/prohibit/ban + O + from -ing)의 필수 준동사 형태" },

  // 4. clauses_relatives
  { lvl: 3, cat: 'clauses_relatives', form: 3, s: "The criterion ______ the scholarship recipients were evaluated remained strictly confidential.", a: "by which", opts: ["by which", "which", "where", "what"], t: "장학생 수혜자들이 평가받았던 기준은 엄격히 기밀로 유지되었다.", f: ["선행사가 기준(criterion)이고 뒤 문장이 완전하며 evaluate by the criterion에서 유래했으므로 by which가 정답입니다.", "which 뒤에는 불완전한 절이 와야 하므로 완전한 수동태 절 앞에 불가합니다.", "where는 장소 선행사에 주로 쓰입니다.", "선행사가 있으므로 what은 불가합니다."], cp: "선행사(criterion) + by which + 완전한 수동태 절", nu: "동사와 결합하는 특정 전치사가 관계대명사 앞으로 이동한 [전치사 + 관계사] 고난도 문형" },
  { lvl: 3, cat: 'clauses_relatives', form: 3, s: "You may invite ______ you believe is qualified to represent the institution.", a: "whoever", opts: ["whoever", "whomever", "whomever that", "anyone"], t: "당신은 그 기관을 대표할 자격이 있다고 당신이 믿는 누구라도 초대할 수 있다.", f: ["you believe는 삽입절이며 뒤에 동사 is qualified의 주어 역할을 해야 하므로 주격 복합관계대명사 whoever가 정답입니다.", "whomever는 목적격이므로 is qualified의 주어가 될 수 없습니다.", "whomever that은 문법적 오류입니다.", "anyone 단독은 뒤의 절을 이끌 수 없습니다."], cp: "whoever + [삽입절 you believe] + is qualified", nu: "삽입절(you believe/think) 뒤에 숨어 있는 주어 자리를 꿰뚫어 보는 복합관계사 whoever" },
  { lvl: 3, cat: 'clauses_relatives', form: 2, s: "The ultimate question is ______ our current resources will suffice for the global expansion.", a: "whether", opts: ["whether", "that", "what", "which"], t: "궁극적인 질문은 우리의 현재 자원이 글로벌 확장에 충분할 것인지 아닌지이다.", f: ["불확실한 의문이나 여부를 나타내며 완전한 1형식 절을 이끄는 명사절 접속사 whether가 정답입니다.", "that은 이미 확정된 사실을 나타낼 때 쓰므로 의문 문맥에 어색합니다.", "what 뒤에는 불완전한 절이 와야 합니다.", "which는 한정된 선택 대상이 있을 때 씁니다."], cp: "is + 명사절 접속사(whether) + 완전한 절", nu: "확정적 사실(that) vs 불확실한 여부(whether)를 구별하는 보어 명사절" },
  { lvl: 3, cat: 'clauses_relatives', form: 3, s: "The historical epoch ______ the Renaissance flourished transformed European philosophy.", a: "during which", opts: ["during which", "which", "whom", "where"], t: "르네상스가 번성했던 그 역사적 시대는 유럽 철학을 완전히 탈바꿈시켰다.", f: ["선행사가 시대(epoch)이고 뒤 문장이 완전하므로 [during + 관계대명사]인 during which가 정답입니다.", "which 뒤에는 불완전한 절이 와야 합니다.", "사물 선행사에 whom 불가입니다.", "where는 공간적 장소에 적합합니다."], cp: "선행사(epoch) + during which(=when) + 완전한 절", nu: "시간/시대 명사를 수식하는 전치사 결합 관계대명사 during which" },

  // 5. connectors
  { lvl: 3, cat: 'connectors', form: 1, s: "______ the widespread skepticism regarding artificial intelligence, adoption rates surged.", a: "Notwithstanding", opts: ["Notwithstanding", "Although", "Whereas", "Even if"], t: "인공지능에 관한 광범위한 회의론에도 불구하고, 도입률은 급등했다.", f: ["뒤에 명사구(the widespread skepticism ...)가 이어지며 양보를 나타내는 고급 전치사 Notwithstanding이 정답입니다.", "Although는 접속사이므로 명사구 앞에 불가합니다.", "Whereas는 대조의 접속사입니다.", "Even if는 양보의 접속사입니다."], cp: "고급 양보 전치사(Notwithstanding) + 명사구, 주절", nu: "despite/in spite of의 격식체 동의어인 Notwithstanding의 전치사 용법" },
  { lvl: 3, cat: 'connectors', form: 3, s: "The agreement shall remain valid ______ either party provides written notice of termination.", a: "unless", opts: ["unless", "if", "provided that", "in case"], t: "어느 한 당사자가 계약 해지의 서면 통지를 제공하지 않는 한, 그 합의는 유효하게 유지된다.", f: ["'만약 ~하지 않는다면(if not)'의 부정 조건을 나타내며 뒤에 절이 오므로 접속사 unless가 정답입니다.", "if는 긍정 조건으로 문맥상 모순입니다.", "provided that은 '~라는 조건으로'입니다.", "in case는 '~에 대비하여'입니다."], cp: "주절 + 조건 접속사(unless: if not) + S + V", nu: "부정의 의미를 내포하는 조건 부사절 접속사 unless의 논리적 귀결" },
  { lvl: 3, cat: 'connectors', form: 1, s: "The research team conducted extensive simulations ______ any potential system failure.", a: "lest they should encounter", opts: ["lest they should encounter", "so that they encountered", "in order to encountering", "for fear to encounter"], t: "연구진은 어떠한 잠재적 시스템 오류라도 마주치지 않도록 광범위한 시뮬레이션을 수행했다.", f: ["'lest S (should) V'는 '~하지 않도록/하기 위하여'라는 부정 목적 구문이므로 lest they should encounter가 정답입니다.", "so that은 긍정 목적 표현입니다.", "in order to 뒤에는 동사원형이 와야 합니다.", "for fear of -ing 형태로 써야 합니다."], cp: "lest S + (should) + 동사원형 ('~하지 않도록')", nu: "수능 및 고난도 영문법 빈출 부정 목적 접속사 lest 구문" },
  { lvl: 3, cat: 'connectors', form: 1, s: "______ the severe macroeconomic headwinds, the startup achieved profitability in its second year.", a: "In spite of", opts: ["In spite of", "Even though", "Much as", "Whereas"], t: "심각한 거시경제적 역풍에도 불구하고, 그 스타트업은 2년 차에 흑자를 달성했다.", f: ["뒤에 명사구(the severe macroeconomic headwinds)가 오므로 전치사구 In spite of가 정답입니다.", "Even though는 접속사로 뒤에 절이 와야 합니다.", "Much as는 양보 접속사입니다.", "Whereas는 접속사입니다."], cp: "전치사구(In spite of) + 명사구, 주절", nu: "명사구를 이끄는 양보 전치사구 In spite of의 구조 분석" },

  // 6. parts_of_speech
  { lvl: 3, cat: 'parts_of_speech', form: 2, s: "The elderly professor has always been very ______ toward his graduate students' research.", a: "considerate", opts: ["considerate", "considerable", "consideration", "considerably"], t: "그 노교수님은 대학원생들의 연구에 대해 항상 매우 사려 깊으셨다(배려심이 넘치셨다).", f: ["사람의 성품이 '사려 깊은, 배려하는'을 뜻하는 형용사는 considerate이므로 considerate가 정답입니다.", "considerable은 '상당한, 많은'이라는 수량/크기 형용사로 문맥에 맞지 않습니다.", "명사는 been 뒤 형용사 보어 자리에 어색합니다.", "부사는 be동사의 주격 보어가 될 수 없습니다."], cp: "be + considerate toward ('~에게 사려 깊은')", nu: "혼동 형용사 considerate(사려 깊은) vs considerable(상당한)의 의미 판별" },
  { lvl: 3, cat: 'parts_of_speech', form: 3, s: "Taking regular breaks during long study sessions is highly ______ for memory retention.", a: "beneficial", opts: ["beneficial", "beneficent", "beneficiary", "benefit"], t: "긴 공부 시간 동안 규칙적인 휴식을 취하는 것은 기억 유지에 대단히 유익하다.", f: ["사물/행위가 '유익한, 도움이 되는'을 뜻하는 형용사는 beneficial이므로 beneficial이 정답입니다.", "beneficent는 '자비로운, 선을 베푸는' 사람의 성품에 주로 씁니다.", "beneficiary는 '수혜자(명사)'입니다.", "명사 benefit은 형용사 보어 자리에 어색합니다."], cp: "is highly + 형용사(beneficial) + for", nu: "혼동 형용사 beneficial(유익한) vs beneficent(자비로운)의 어휘 구별" },
  { lvl: 3, cat: 'parts_of_speech', form: 2, s: "The financial committee decided that such extravagant spending was not ______.", a: "permissible", opts: ["permissible", "permissive", "permission", "permissively"], t: "재정위원회는 그러한 낭비적인 지출은 결코 허용될 수 없다고 결정했다.", f: ["행위나 규정이 '허용되는, 용인되는'을 뜻하는 형용사는 permissible이므로 permissible이 정답입니다.", "permissive는 '관대한, 허용적인(성격)'을 뜻하므로 사물 지출에 부적절합니다.", "명사는 was not 뒤 보어로 어색합니다.", "부사는 보어 불가입니다."], cp: "was not + 형용사 보어(permissible)", nu: "혼동 파생 형용사 permissible(허용되는) vs permissive(관대한)의 격차" },
  { lvl: 3, cat: 'parts_of_speech', form: 3, s: "The diplomat handled the international crisis with remarkable ______.", a: "competence", opts: ["competence", "competent", "competently", "competition"], t: "그 외교관은 놀라운 역량(능력)을 발휘하여 그 국제 위기를 처리했다.", f: ["전치사 with와 형용사 remarkable 뒤 명사 자리이므로 능력/역량을 뜻하는 competence가 정답입니다.", "형용사 competent는 전치사+형용사 뒤에 불가합니다.", "부사는 전치사의 목적어 불가입니다.", "competition은 '경쟁/대회'로 문맥에 모순입니다."], cp: "with + remarkable + 명사(competence)", nu: "전치사의 목적어 자리와 파생 명사 competence(역량)의 어휘 쓰임" },

  // 7. modals_subjunctive
  { lvl: 3, cat: 'modals_subjunctive', form: 3, s: "The chief compliance officer recommended that the internal audit ______ quarterly.", a: "be conducted", opts: ["be conducted", "is conducted", "was conducted", "conducted"], t: "최고 준법 감시관은 내부 감사가 분기별로 시행되어야 한다고 권고했다.", f: ["권고 동사 recommend 뒤의 that절이므로 (should) 생략에 따른 동사원형 수동태 be conducted가 정답입니다.", "직설법 is는 당위성 that절에 쓸 수 없습니다.", "주절이 과거라 해도 당위성 원형 규칙이 우선합니다.", "능동형은 목적어가 없어 비문입니다."], cp: "recommend that S + (should) be p.p.", nu: "주장/제안/권고 동사 뒤 that절의 당위성 가정법 현재(동사원형) 공식" },
  { lvl: 3, cat: 'modals_subjunctive', form: 3, s: "If the government had not intervened, the financial market ______ collapsed completely.", a: "would have", opts: ["would have", "will have", "would", "had"], t: "정부가 개입하지 않았었더라면, 금융시장은 완전히 붕괴했을 텐데.", f: ["조건절이 had not intervened(가정법 과거완료)이므로 주절에는 [would have + p.p.(collapsed)]인 would have가 정답입니다.", "미래완료 will have는 가정법 과거완료와 결합 불가입니다.", "would 단독은 과거완료 조건절과 시제 불일치입니다.", "had 단독은 조동사 불가입니다."], cp: "If S + had p.p., S + would have p.p.", nu: "과거 사실의 반대를 가정한 가정법 과거완료의 귀결절 구조" },
  { lvl: 3, cat: 'modals_subjunctive', form: 1, s: "Without your timely financial assistance, our company ______ bankrupt last year.", a: "would have gone", opts: ["would have gone", "would go", "will go", "had gone"], t: "당신의 시의적절한 재정 지원이 없었더라면, 우리 회사는 작년에 파산했을 것이다.", f: ["last year 과거 시점의 가정이므로 Without(=If it had not been for) 뒤 귀결절은 would have gone이 정답입니다.", "would go는 현재 사실 반대(가정법 과거)에 쓰입니다.", "will go는 단순 미래입니다.", "had gone은 단독 주절에 불가합니다."], cp: "Without + 명사, S + would have p.p. + last year", nu: "Without/But for 구문이 이끄는 과거 사실에 대한 가정법 과거완료" },
  { lvl: 3, cat: 'modals_subjunctive', form: 3, s: "It is imperative that every medical personnel ______ strict sterilization procedures.", a: "follow", opts: ["follow", "follows", "followed", "is following"], t: "모든 의료 인력이 엄격한 멸균 절차를 따르는 것은 절대적으로 필수적이다.", f: ["'It is imperative that S + (should) 동사원형' 당위성 형용사 구문이므로 동사원형 follow가 정답입니다.", "personnel이 단수 취급되더라도 당위성 원형 규칙에 따라 follows는 비문입니다.", "과거형은 당위성 구문에 불가합니다.", "진행형은 불가합니다."], cp: "It is imperative that S + (should) + 동사원형", nu: "필수/중요성 형용사(imperative/essential/vital) 뒤 that절의 동사원형 규칙" },

  // 8. special_structures
  { lvl: 3, cat: 'special_structures', form: 1, s: "Hardly ______ the stage when the enthusiastic audience erupted into thunderous applause.", a: "had the singer stepped onto", opts: ["had the singer stepped onto", "the singer had stepped onto", "did the singer step onto", "was the singer stepped onto"], t: "그 가수가 무대에 발을 내딛자마자 열광적인 관객들이 우레와 같은 박수를 터뜨렸다.", f: ["'Hardly had S p.p. when ...' (~하자마자 ~했다) 구문이므로 had the singer stepped onto가 정답입니다.", "평서문 어순은 Hardly 도치 규칙 위반입니다.", "did step은 대과거를 나타내지 못합니다.", "수동태는 가수가 밟혀진 것이 되어 비문입니다."], cp: "Hardly had + S + p.p. ... when + 과거동사", nu: "동작의 즉각적인 연속을 나타내는 Hardly/Scarcely ... when/before 도치 구문" },
  { lvl: 3, cat: 'special_structures', form: 1, s: "No sooner ______ the contract than unexpected legal disputes emerged.", a: "had the partners signed", opts: ["had the partners signed", "the partners had signed", "did the partners sign", "have the partners signed"], t: "동업자들이 계약서에 서명하자마자 예상치 못한 법적 분쟁이 발생했다.", f: ["'No sooner had S p.p. than ...' 구문으로 문두 No sooner에 의해 도치되므로 had the partners signed가 정답입니다.", "평서문 어순은 No sooner 도치 위반입니다.", "did는 대과거 표현에 부적절합니다.", "현재완료는 과거 기준 시점(emerged)에 모순입니다."], cp: "No sooner had + S + p.p. ... than + 과거동사", nu: "No sooner ... than 구문의 대과거 도치 어순" },
  { lvl: 3, cat: 'special_structures', form: 1, s: "Not until the late nineteenth century ______ electricity begin to transform domestic life.", a: "did", opts: ["did", "was", "has", "had"], t: "19세기 후반이 되어서야 비로소 전기가 가정생활을 변화시키기 시작했다.", f: ["'Not until ~' 구문이 문두에 와서 주절이 도치되며 뒤에 일반동사 원형 begin이 있으므로 조동사 did가 정답입니다.", "be동사 was는 일반동사 원형 begin 앞에 불가합니다.", "과거 역사적 사실에 현재완료 has는 불가합니다.", "had 뒤에는 p.p.가 와야 하므로 원형 begin 앞에 불가합니다."], cp: "Not until + 시간부사구 + did + 주어 + 동사원형", nu: "Not until 구문이 문두로 이동할 때 주절에 발생하는 주어-조동사 도치" },
  { lvl: 3, cat: 'special_structures', form: 1, s: "Only by implementing comprehensive educational reforms ______ bridge the widening socioeconomic gap.", a: "can our society", opts: ["can our society", "our society can", "our society could", "does our society"], t: "포괄적인 교육 개혁을 시행함으로써만 우리 사회는 벌어지는 사회경제적 격차를 좁힐 수 있다.", f: ["'Only + 전치사구'가 문두에 강조되어 조동사와 주어가 도치되므로 can our society가 정답입니다.", "평서문 어순은 Only 부사구 도치 규칙 위반입니다.", "평서문 어순은 불가합니다.", "가능성의 의미(bridge)에는 can이 자연스럽습니다."], cp: "Only + by -ing + can + 주어 + 동사원형", nu: "수단/방법을 한정하는 Only 부사구 문두 배치에 따른 조동사 도치" },

  // 9. verb_patterns
  { lvl: 3, cat: 'verb_patterns', form: 3, s: "The manufacturing plant must strictly ______ with all international environmental standards.", a: "comply", opts: ["comply", "comply to", "conform with to", "abide"], t: "그 제조 공장은 모든 국제 환경 기준을 엄격하게 준수해야 한다.", f: ["'~을 준수하다/따르다'는 자동사 comply와 전치사 with가 결합하므로 comply가 정답입니다.", "comply는 to와 결합하지 않습니다.", "conform with to는 잘못된 형태입니다.", "abide는 by와 결합합니다(abide by)."], cp: "comply with + 규정/기준 ('~을 준수하다')", nu: "규정 준수를 나타내는 자동사 + 전치사 필수 어휘 comply with vs abide by" },
  { lvl: 3, cat: 'verb_patterns', form: 3, s: "The unexpected market downturn greatly ______ the company's annual revenue projections.", a: "affected", opts: ["affected", "affected to", "effected on", "had effect"], t: "예상치 못한 시장 침체는 회사의 연간 매출 전망에 큰 영향을 미쳤다.", f: ["affect는 타동사로 전치사 없이 목적어를 바로 취하므로 affected가 정답입니다.", "affect 뒤에 to를 붙이면 비문입니다.", "effect는 명사이거나 '초래하다'라는 뜻의 타동사입니다.", "had an effect on 형태로 써야 합니다."], cp: "타동사(affect) + 목적어 ('~에 영향을 미치다')", nu: "타동사 affect(~에 영향을 미치다) vs 명사 effect(영향, 효과)의 정확한 구별" },
  { lvl: 3, cat: 'verb_patterns', form: 3, s: "All participating delegates must ______ by the ethical guidelines established by the committee.", a: "abide", opts: ["abide", "abide with", "comply", "conform"], t: "모든 참가 대표단은 위원회가 수립한 윤리 지침을 준수해야 한다.", f: ["전치사 by와 결합하여 규칙을 '준수하다'를 뜻하는 자동사는 abide이므로 abide가 정답입니다.", "abide with는 부자연스럽습니다.", "comply는 with와 결합합니다.", "conform은 to/with와 결합합니다."], cp: "abide by + 규정 ('~을 지키다, 준수하다')", nu: "전치사 by와 호응하는 필수 자동사 abide by" },
  { lvl: 3, cat: 'verb_patterns', form: 3, s: "The new residential zoning law will ______ into effect starting from next January.", a: "come", opts: ["come", "bring", "put", "take"], t: "새로운 주거 지역 구획법은 내년 1월부터 효력을 발휘할 것이다(발효될 것이다).", f: ["법률이나 규칙이 '발효되다/시행되다'는 자동사구 come into effect이므로 come이 정답입니다.", "bring into effect는 타동사구로 주어가 법률일 때는 수동태(be brought into effect)로 써야 합니다.", "put into effect도 타동사구입니다.", "take effect는 전치사 into 없이 씁니다."], cp: "come into effect ('발효되다, 시행되다')", nu: "자동사구 come into effect vs 타동사구 bring A into effect의 구조적 차이" },

  // 10. parallel_agreement
  { lvl: 3, cat: 'parallel_agreement', form: 3, s: "The candidate's success depends not on his charisma but on his ______ and integrity.", a: "competence", opts: ["competence", "competent", "competently", "competing"], t: "그 후보자의 성공은 그의 카리스마가 아니라 그의 역량과 진실성에 달려 있다.", f: ["전치사 on의 목적어로 소유격 his 뒤에 명사 integrity와 and로 병렬을 이루므로 명사 competence가 정답입니다.", "형용사는 명사 integrity와 병렬을 이룰 수 없습니다.", "부사는 병렬 불가입니다.", "동명사는 integrity와 대등한 명사 병렬에 어색합니다."], cp: "not on A(명사) but on B(명사)", nu: "not A but B 구문에서 전치사구 및 명사구 간의 완벽한 문법적 대등성" },
  { lvl: 3, cat: 'parallel_agreement', form: 3, s: "The executive was praised not only for expanding revenue but also for ______ corporate governance.", a: "reforming", opts: ["reforming", "to reform", "reform", "reformed"], t: "그 임원은 매출을 신장시킨 것뿐만 아니라 기업 지배구조를 개혁한 것으로도 칭송받았다.", f: ["'not only for A(-ing) but also for B(-ing)'에서 전치사 for 뒤 동명사 expanding과 병렬이므로 reforming이 정답입니다.", "to부정사는 전치사 for 뒤에 올 수 없습니다.", "동사원형은 for 뒤에 올 수 없습니다.", "과거분사는 목적어(governance)를 취하는 동명사 자리에 부적절합니다."], cp: "not only for A(-ing) but also for B(-ing)", nu: "상관접속사 뒤 전치사구 내 동명사의 정밀한 형태적 일치" },
  { lvl: 3, cat: 'parallel_agreement', form: 2, s: "The technological capabilities of modern smartphones far exceed ______ of early personal computers.", a: "those", opts: ["those", "that", "it", "them"], t: "현대 스마트폰의 기술적 역량은 초기 개인용 컴퓨터의 기술적 역량을 훨씬 능가한다.", f: ["비교 대상인 복수명사(The technological capabilities)를 대신 가리키므로 복수 대명사 those가 정답입니다.", "that은 단수명사를 대신할 때 씁니다.", "it은 후치 수식어(of...)를 동반하지 못합니다.", "them은 특정 대상을 가리킬 뿐 수식어구 동반 비교 대명사로 쓸 수 없습니다."], cp: "복수 비교 대상(The capabilities) ➔ those of ...", nu: "비교 대상의 수(단수 that vs 복수 those)에 따른 정확한 대명사 일치" },
  { lvl: 3, cat: 'parallel_agreement', form: 3, s: "Effective leadership requires both articulating a clear vision and ______ ethical accountability.", a: "demonstrating", opts: ["demonstrating", "demonstrate", "to demonstrate", "demonstrated"], t: "효과적인 리더십은 명확한 비전을 제시하는 것과 윤리적 책무성을 입증하는 것 둘 다를 필요로 한다.", f: ["both A and B에서 동명사 목적어 articulating과 대등한 형태를 이루어야 하므로 demonstrating이 정답입니다.", "동사원형은 articulating과 병렬 불가입니다.", "to부정사는 동명사와 병렬 불가입니다.", "과거분사는 능동 목적어를 취하는 동명사 병렬에 부적절합니다."], cp: "both A(-ing) and B(-ing)", nu: "both A and B 구문에서 동명사 목적어 간의 대등한 병렬 결합" },


  // =============================================================
  // 🔴 LEVEL 4 (40 Qs: 10 Categories x 4)
  // =============================================================
  // 1. subject_verb_agreement
  { lvl: 4, cat: 'subject_verb_agreement', form: 2, s: "Neither the principal investigator nor the data analysts ______ privy to the proprietary algorithm.", a: "were", opts: ["were", "was", "is", "being"], t: "책임 연구원도 데이터 분석가들도 그 독점 알고리즘에 대해 알지(접근하지) 못했다.", f: ["'Neither A nor B' 구문에서 동사의 수는 가까운 B(the data analysts: 복수)에 일치시키므로 were가 정답입니다.", "단수 was는 복수 명사 analysts와 수일치 위반입니다.", "is는 단수이자 시제 불일치입니다.", "being 단독은 본동사 불가입니다."], cp: "Neither A nor B(복수 주어) + were", nu: "근자일치 원칙에 따른 상관접속사 Neither A nor B의 엄격한 수일치" },
  { lvl: 4, cat: 'subject_verb_agreement', form: 2, s: "A plethora of empirical evidence gathered across multiple trials ______ the initial hypothesis.", a: "corroborates", opts: ["corroborates", "corroborate", "corroborating", "are corroborated"], t: "다수의 시험에 걸쳐 수집된 풍부한 실증적 증거는 초기 가설을 강력하게 뒷받침한다.", f: ["핵심 주어가 불가산 단수명사(evidence)이므로 단수동사 corroborates가 정답입니다.", "trials에 현혹되지 않고 핵심 주어 evidence에 맞춰야 하므로 복수형 corroborate는 오류입니다.", "단독 -ing는 본동사 불가입니다.", "증거가 가설을 뒷받침하는 능동이므로 수동태는 비문입니다."], cp: "A plethora of + 불가산 명사(evidence) + 단수동사(corroborates)", nu: "다층적 수식어 거품 속에서 핵심 불가산 주어의 단수성을 판별하는 킬러 수일치" },
  { lvl: 4, cat: 'subject_verb_agreement', form: 3, s: "More than one senior executive ______ expressed serious reservations about the merger.", a: "has", opts: ["has", "have", "are", "having"], t: "한 명 이상의 고위 임원이 그 합병에 대해 심각한 우려를 표명했다.", f: ["'More than one + 단수명사'는 의미상 복수라도 문법적으로 단수 취급하므로 has가 정답입니다.", "More than one 뒤의 단수명사(executive)에 맞춰야 하므로 have는 문법 규칙 위반입니다.", "are는 p.p. expressed 앞에 완료형 조동사가 아니므로 불가합니다.", "단독 -ing는 동사 불가입니다."], cp: "More than one + 단수명사(executive) + has p.p.", nu: "형식적 단수 일치 원칙을 따르는 'More than one + 단수명사' 특수 수일치" },
  { lvl: 4, cat: 'subject_verb_agreement', form: 2, s: "The overarching objective of the newly instituted environmental regulations ______ carbon neutrality.", a: "is", opts: ["is", "are", "were", "being"], t: "새롭게 제정된 환경 규정들의 가장 주된 목표는 탄소 중립을 달성하는 것이다.", f: ["핵심 주어가 단수명사(The overarching objective)이므로 복수 regulations를 걷어내고 단수 is가 정답입니다.", "전치사구 속의 regulations에 낚여 are를 고르면 오답입니다.", "현재 규정의 목표이므로 과거 were는 부적절합니다.", "being 단독은 동사 불가입니다."], cp: "The objective(단수) + of regulations + is", nu: "복합 수식어구에 가려진 진주어 The objective를 찾아내는 수일치" },

  // 2. tense_voice
  { lvl: 4, cat: 'tense_voice', form: 3, s: "By the end of this fiscal quarter, the restructuring committee ______ the comprehensive audit.", a: "will have concluded", opts: ["will have concluded", "concluded", "has concluded", "concludes"], t: "이번 회계 분기 말까지, 구조조정 위원회는 포괄적 감사를 완료했을 것이다.", f: ["'By the end of + 미래 시점' 단서가 있으므로 미래 특정 시점까지의 완료를 나타내는 미래완료 will have concluded가 정답입니다.", "단순 과거는 미래 시점과 모순입니다.", "현재완료는 미래 기준 시점에 쓸 수 없습니다.", "단순 현재는 특정 시점 이전의 선완료를 나타내지 못합니다."], cp: "By the end of 미래시점 + will have p.p.", nu: "미래 완료 기준 시점 부사구와 결합하는 미래완료 시제 공식" },
  { lvl: 4, cat: 'tense_voice', form: 3, s: "The diplomatic memorandum is understood ______ by the ambassador prior to the summit.", a: "to have been drafted", opts: ["to have been drafted", "to be drafted", "to draft", "having drafted"], t: "그 외교 비망록은 정상회담 이전에 대사에 의해 작성되었던 것으로 이해된다.", f: ["현재 이해되는(is understood) 것보다 이전에 작성된 수동 관계이므로 완료 수동 부정사 to have been drafted가 정답입니다.", "to be drafted는 주절과 동시 시점이 되어 prior to(이전)와 모순입니다.", "비망록은 작성되는 대상이므로 능동은 불가합니다.", "understood 뒤의 보어로 완료부정사 형태가 적합합니다."], cp: "is understood + to have been p.p. (완료 수동 부정사)", nu: "주절 시점(현재)보다 앞선 과거 시점의 수동 행위를 나타내는 완료 수동 부정사" },
  { lvl: 4, cat: 'tense_voice', form: 3, s: "The corporate embezzlement scandal was revealed ______ by internal whistleblowers months earlier.", a: "to have been uncovered", opts: ["to have been uncovered", "to uncover", "to be uncovered", "having uncovered"], t: "그 기업 횡령 스캔들은 수개월 전에 내부 고발자들에 의해 밝혀졌던 것으로 드러났다.", f: ["드러난 과거(was revealed)보다 수개월 전에 밝혀진 수동 관계이므로 완료 수동 부정사 to have been uncovered가 정답입니다.", "스캔들은 밝혀지는 대상이므로 능동 to uncover는 불가합니다.", "단순 수동 부정사는 earlier와 시제 모순입니다.", "to부정사 보어 자리에 -ing는 어색합니다."], cp: "was revealed + to have been p.p. + earlier", nu: "과거보다 더 앞선 대과거의 수동적 사건을 진술하는 완료 수동 부정사" },
  { lvl: 4, cat: 'tense_voice', form: 5, s: "The magistrate ordered the contentious evidence ______ from the official court record.", a: "expunged", opts: ["expunged", "expunge", "to expunge", "expunging"], t: "판사는 논란이 되는 증거가 공식 법정 기록에서 삭제(말소)되도록 명령했다.", f: ["목적어(the evidence)와 보어가 수동 관계(증거는 말소됨)이므로 과거분사 expunged가 정답입니다.", "증거가 능동으로 말소하는 주체가 아니므로 원형은 불가합니다.", "수동 관계에 능동 to부정사는 불가합니다.", "진행형은 수동 의미에 부적절합니다."], cp: "order + O(증거) + p.p.(말소된)", nu: "목적어와 목적격 보어 사이의 수동 관계를 나타내는 5형식 과거분사 보어" },

  // 3. verbals
  { lvl: 4, cat: 'verbals', form: 1, s: "______ no formal objections from the shareholders, the board ratified the acquisition.", a: "There being", opts: ["There being", "Being", "Having been", "It being"], t: "주주들로부터 공식적인 이의 제기가 없었기 때문에, 이사회는 인수를 비준했다.", f: ["'There is no objection' 구문에서 접속사와 동사가 변형된 독립분사구문이므로 There being이 정답입니다.", "Being만 쓰면 주어가 the board가 되어 비문이 됩니다.", "Having been은 주어가 모순됩니다.", "It being은 날씨/비인칭 주어에 쓰이므로 존재 구문 There에 부적절합니다."], cp: "독립분사구문(There being + 명사 주어) + 주절", nu: "유도부사 There is 구문이 분사구문으로 전환된 There being 독립분사구문" },
  { lvl: 4, cat: 'verbals', form: 3, s: "The research team is committed to ______ sustainable solutions for plastic degradation.", a: "devising", opts: ["devising", "devise", "devised", "have devised"], t: "연구팀은 플라스틱 분해를 위한 지속 가능한 해결책을 고안하는 데 헌신하고 있다.", f: ["'be committed to'에서 to는 전치사이므로 동사원형이 아닌 동명사 devising이 정답입니다.", "to를 부정사로 착각하여 동사원형 devise를 고르면 오답입니다.", "과거분사는 전치사 to의 목적어가 될 수 없습니다.", "현재완료는 전치사 뒤에 올 수 없습니다."], cp: "be committed to + -ing (전치사 to 필수 동명사)", nu: "to부정사가 아닌 전치사 to로 끝나는 관용 표현(be committed to -ing)의 함정" },
  { lvl: 4, cat: 'verbals', form: 3, s: "Many developing nations look forward to ______ advanced green technology transfers.", a: "receiving", opts: ["receiving", "receive", "received", "have received"], t: "많은 개발도상국들은 선진 친환경 기술 이전을 받기를 고대하고 있다.", f: ["'look forward to'의 to는 전치사이므로 동명사 receiving이 정답입니다.", "to 뒤에 동사원형 receive를 쓰면 대표적인 어법 위반입니다.", "과거분사는 전치사 뒤에 올 수 없습니다.", "have received는 전치사 뒤에 불가합니다."], cp: "look forward to + -ing (전치사 to 필수 동명사)", nu: "편입/공무원/토익 최빈출 전치사 to 뒤 동명사 필수 규칙" },
  { lvl: 4, cat: 'verbals', form: 1, s: "______ for his seminal contributions to quantum mechanics, the physicist was lauded globally.", a: "Acclaimed", opts: ["Acclaimed", "Acclaiming", "Having acclaimed", "To acclaim"], t: "양자역학에 대한 독창적인 공헌으로 찬사를 받았기 때문에, 그 물리학자는 전 세계적으로 칭송받았다.", f: ["주절의 주어(the physicist)가 찬사를 받는 수동 관계이므로 과거분사로 시작하는 수동 분사구문 Acclaimed가 정답입니다.", "물리학자가 스스로 찬사하는 능동이 아니므로 Acclaiming은 비문입니다.", "완료 능동분사는 목적어가 없어 비문입니다.", "to부정사는 이유 분사구문으로 어색합니다."], cp: "수동 분사구문(Acclaimed for ...) + 주절", nu: "주어와의 수동 관계를 간결하게 압축하는 과거분사 분사구문" },

  // 4. clauses_relatives
  { lvl: 4, cat: 'clauses_relatives', form: 3, s: "The theoretical paradigm ______ the entire computational model was structured proved flawed.", a: "upon which", opts: ["upon which", "which", "whom", "where"], t: "전체 계산 모델이 구축되었던 그 이론적 패러다임은 결함이 있는 것으로 드러났다.", f: ["선행사가 paradigm이고 'be structured upon the paradigm'에서 전치사 upon이 앞으로 이동했으므로 upon which가 정답입니다.", "which 뒤에는 불완전한 절이 와야 하므로 완전한 수동태 절 앞에 불가합니다.", "사물 선행사에 whom 불가입니다.", "where는 공간적 장소에 주로 쓰입니다."], cp: "선행사(paradigm) + upon which + 완전한 수동태 절", nu: "동사구(be structured upon)의 전치사가 관계사 앞으로 도치된 고급 관계사절" },
  { lvl: 4, cat: 'clauses_relatives', form: 3, s: "The CEO appointed an executive advisor ______ integrity and strategic acumen were unquestioned.", a: "whose", opts: ["whose", "who", "whom", "which"], t: "대표이사는 진실성과 전략적 감각이 의심할 여지 없는 임원 고문을 임명했다.", f: ["선행사(executive advisor)와 뒤의 명사구(integrity and strategic acumen) 사이의 소유격을 나타내므로 whose가 정답입니다.", "who 뒤에는 주어가 생략되어야 하는데 명사구가 바로 이어집니다.", "목적격 whom은 소유격 자리에 올 수 없습니다.", "사람 선행사에 which는 쓸 수 없습니다."], cp: "선행사(advisor) + whose + 명사구 + were unquestioned", nu: "명사구 주어를 소유격으로 연결하는 소유격 관계대명사 whose의 정밀한 용법" },
  { lvl: 4, cat: 'clauses_relatives', form: 3, s: "The legal doctrine ______ this precedent was established dates back to the seventeenth century.", a: "wherein", opts: ["wherein", "which", "whose", "what"], t: "이 판례가 확립되었던 그 법리적 원칙은 17세기로 거슬러 올라간다.", f: ["선행사(doctrine) 내에서 판례가 확립된 완전한 절을 이끄는 격식체 관계부사 wherein(=in which)이 정답입니다.", "which 뒤에는 불완전한 절이 와야 합니다.", "소유격 whose 뒤에는 명사가 이어져야 합니다.", "선행사가 있으므로 what은 불가합니다."], cp: "선행사(doctrine) + wherein(=in which) + 완전한 절", nu: "법률 및 학술 전문 문서에서 in which를 대체하는 고급 관계부사 wherein" },
  { lvl: 4, cat: 'clauses_relatives', form: 3, s: "We must distinguish between what is legally mandated and ______ is ethically imperative.", a: "what", opts: ["what", "that", "which", "whom"], t: "우리는 법적으로 의무화된 것과 윤리적으로 필수적인 것을 반드시 구별해야 한다.", f: ["and 뒤에서 주어가 빠진 불완전한 절을 이끌며 between의 목적어 역할을 하는 관계대명사 what이 정답입니다.", "접속사 that 뒤에는 완전한 절이 와야 합니다.", "선행사가 없는 자리에 which는 불가합니다.", "목적격 whom은 주어 자리에 올 수 없습니다."], cp: "between what is A and what is B (명사절 병렬)", nu: "전치사 between 뒤에서 선행사를 포함하는 명사절 what의 정밀한 병렬 구조" },

  // 5. connectors
  { lvl: 4, cat: 'connectors', form: 1, s: "The transaction will proceed ______ that all regulatory compliance benchmarks are fully met.", a: "provided", opts: ["provided", "in case of", "despite", "whereas"], t: "모든 규제 준수 기준이 완전히 충족된다는 조건 하에 그 거래는 진행될 것이다.", f: ["'provided that'은 if를 대체하는 격식체 조건 접속사이므로 provided가 정답입니다.", "in case of는 전치사이므로 that절 앞에 불가합니다.", "despite는 전치사입니다.", "whereas는 대조 접속사입니다."], cp: "주절 + provided (that) + S + V", nu: "계약서 및 공공 문서에서 조건을 규정하는 접속사 provided that" },
  { lvl: 4, cat: 'connectors', form: 1, s: "______ the formidable barriers to market entry, the venture achieved dominant market share.", a: "Notwithstanding", opts: ["Notwithstanding", "Although", "Even though", "Whereas"], t: "시장 진입에 대한 가공할 만한 장벽에도 불구하고, 그 벤처기업은 지배적인 시장 점유율을 달성했다.", f: ["뒤에 명사구(the formidable barriers ...)가 이어지며 양보를 나타내는 고급 전치사 Notwithstanding이 정답입니다.", "Although는 접속사이므로 명사구 앞에 불가합니다.", "Even though는 접속사입니다.", "Whereas는 접속사입니다."], cp: "양보 전치사(Notwithstanding) + 명사구, 주절", nu: "격식체 양보 전치사 Notwithstanding의 구조 판별" },
  { lvl: 4, cat: 'connectors', form: 1, s: "The pharmaceutical compound was discarded ______ toxicity risks identified during trials.", a: "owing to", opts: ["owing to", "because", "although", "while"], t: "그 의약 화합물은 임상시험 중 확인된 독성 위험 때문에 폐기되었다.", f: ["뒤에 명사구(toxicity risks identified ...)가 이어지며 원인을 나타내는 전치사구 owing to가 정답입니다.", "because는 접속사이므로 명사구 앞에는 불가합니다.", "although는 접속사이자 양보 의미입니다.", "while은 접속사입니다."], cp: "주절 + 전치사구(owing to) + 명사구", nu: "원인을 나타내는 격식체 전치사구 owing to vs 접속사 because" },
  { lvl: 4, cat: 'connectors', form: 3, s: "The diplomat spoke with extreme ambiguity ______ commitments might constrain future negotiations.", a: "lest binding", opts: ["lest binding", "so that binding", "in case of binding", "for fear to binding"], t: "그 외교관은 구속력 있는 약속이 향후 협상을 제약하지 않도록 극도의 모호성을 띠고 발언했다.", f: ["'lest S (should) V'는 '~하지 않도록'을 뜻하는 부정 목적 접속사이므로 lest binding (commitments constrain)이 정답입니다.", "so that은 긍정 목적입니다.", "in case of는 전치사입니다.", "for fear to는 비문입니다."], cp: "lest + 주어 + (should) + 동사원형", nu: "국제정치 및 고급 영문에서 의도적 회피를 나타내는 부정 목적 접속사 lest" },

  // 6. parts_of_speech
  { lvl: 4, cat: 'parts_of_speech', form: 2, s: "Given the volatile geopolitical landscape, such defensive precautions are quite ______.", a: "sensible", opts: ["sensible", "sensitive", "sensibility", "sensibly"], t: "불안정한 지정학적 상황을 고려할 때, 그러한 방어적 예방 조치는 대단히 현명하다(합리적이다).", f: ["판단이나 조치가 '현명한, 합리적인, 분별 있는'을 뜻하는 형용사는 sensible이므로 sensible이 정답입니다.", "sensitive는 '민감한, 예민한'을 뜻하므로 조치가 현명하다는 문맥에 어색합니다.", "명사는 are quite 뒤 보어로 어색합니다.", "부사는 be동사 보어 불가입니다."], cp: "precautions are quite + sensible ('현명한, 합리적인')", nu: "혼동 형용사 sensible(현명한, 분별력 있는) vs sensitive(민감한, 예민한)의 킬러 어휘" },
  { lvl: 4, cat: 'parts_of_speech', form: 3, s: "The research institute enjoys a highly ______ reputation throughout the global scientific community.", a: "respectable", opts: ["respectable", "respectful", "respective", "respectfully"], t: "그 연구소는 전 세계 과학계 전반에서 대단히 존경할 만한(훌륭한) 명성을 누리고 있다.", f: ["대상/명성이 '존경할 만한, 훌륭한'을 뜻하는 형용사는 respectable이므로 respectable이 정답입니다.", "respectful은 '공손한, 예의 바른(태도)'을 뜻하므로 reputation 수식에 부적절합니다.", "respective는 '각각의, 개별적인'을 뜻합니다.", "부사는 명사 reputation을 수식할 수 없습니다."], cp: "a highly + respectable + reputation", nu: "3대 혼동 파생어 respectable(존경할 만한) vs respectful(공손한) vs respective(각각의)" },
  { lvl: 4, cat: 'parts_of_speech', form: 2, s: "The proposed regulatory changes are deemed ______ with existing constitutional provisions.", a: "incompatible", opts: ["incompatible", "incompetent", "incompatibility", "incompatibly"], t: "제안된 규제 변경안은 기존 헌법 조항과 양립할 수 없는(모순되는) 것으로 간주된다.", f: ["두 법규가 '양립할 수 없는, 모순되는'을 뜻하며 with와 결합하는 형용사는 incompatible이므로 incompatible이 정답입니다.", "incompetent는 '무능한' 사람에 씁니다.", "명사는 deemed 뒤 보어로 부적절합니다.", "부사는 5형식 수동 보어 불가입니다."], cp: "be deemed + incompatible with ('~와 양립할 수 없는')", nu: "전문 법률/학술 어휘 incompatible with vs incompetent" },
  { lvl: 4, cat: 'parts_of_speech', form: 3, s: "The executive committee deliberated upon the proposal with extraordinary ______.", a: "thoroughness", opts: ["thoroughness", "thorough", "thoroughly", "through"], t: "집행위원회는 비범할 정도의 철저함을 가지고 그 제안서를 심의했다.", f: ["전치사 with와 형용사 extraordinary 뒤 명사 자리이므로 추상명사 thoroughness가 정답입니다.", "형용사 thorough는 전치사+형용사 뒤에 불가합니다.", "부사는 전치사의 목적어 불가입니다.", "through는 전치사입니다."], cp: "with + extraordinary + 명사(thoroughness)", nu: "전치사의 목적어로 위치하는 파생 명사 thoroughness(철저함)의 형태" },

  // 7. modals_subjunctive
  { lvl: 4, cat: 'modals_subjunctive', form: 3, s: "______ the regulatory authorities have any inquiries, our legal counsel will respond immediately.", a: "Should", opts: ["Should", "Were", "Had", "If should"], t: "혹시라도 규제 당국이 문의 사항이 있다면, 우리의 법률 고문이 즉시 답변할 것이다.", f: ["미래의 희박한 가능성을 나타내는 조건절에서 If가 생략되어 [Should + S + 동사원형]으로 도치되므로 Should가 정답입니다.", "Were는 가정법 과거에 쓰이며 뒤에 to부정사가 와야 합니다.", "Had는 과거완료에 쓰이며 뒤에 p.p.가 와야 합니다.", "If should는 If와 도치 조동사가 중복된 비문입니다."], cp: "Should + S + 동사원형(have) ... (If 생략 도치)", nu: "If가 생략되었을 때 문두로 튀어나오는 가정법 조건절 도치(Should S V)" },
  { lvl: 4, cat: 'modals_subjunctive', form: 3, s: "______ the semiconductor shortage not occurred, our production quota would have been met.", a: "Had", opts: ["Had", "Were", "Should", "If had"], t: "반도체 품귀 현상이 발생하지 않았었더라면, 우리의 생산 할당량은 충족되었을 텐데.", f: ["가정법 과거완료 조건절 'If the shortage had not occurred'에서 If가 생략되어 도치되므로 Had가 정답입니다.", "Were는 가정법 과거에 씁니다.", "Should는 미래 가정에 씁니다.", "If had는 중복 오류입니다."], cp: "Had + S + not p.p. ... (가정법 과거완료 If 생략 도치)", nu: "편입 및 공무원 킬러 문형인 가정법 과거완료의 If 생략 도치(Had S p.p.)" },
  { lvl: 4, cat: 'modals_subjunctive', form: 3, s: "______ it not for international humanitarian aid, countless refugees would perish.", a: "Were", opts: ["Were", "Had", "Should", "Was"], t: "국제적인 인도주의적 구호가 없다면, 수많은 난민들이 목숨을 잃을 텐데.", f: ["'If it were not for'에서 If가 생략되어 도치된 형태이므로 Were it not for가 정답입니다.", "Had는 과거 사실 반대(Had it not been for)에 씁니다.", "Should it not for는 문법에 없는 표현입니다.", "가정법 과거 공식에서 be동사는 Were가 원칙입니다."], cp: "Were it not for + 명사 ('~이 없다면' = If it were not for)", nu: "Without/But for와 동의어인 가정법 과거 If 생략 도치 Were it not for" },
  { lvl: 4, cat: 'modals_subjunctive', form: 3, s: "The compliance officer mandated that all financial transactions ______ authenticated instantly.", a: "be", opts: ["be", "are", "were", "being"], t: "준법 감시관은 모든 금융 거래가 즉각적으로 인증되어야 한다고 명령했다.", f: ["명령 동사 mandate 뒤의 that절이므로 (should) 생략에 따른 동사원형 be가 정답입니다.", "직설법 are는 당위성 절에 불가합니다.", "주절이 과거라도 당위성 원형 규칙이 우선합니다.", "being 단독은 동사 불가입니다."], cp: "mandate that S + (should) be p.p.", nu: "명령 동사 mandate 뒤 that절의 동사원형(가정법 현재) 필수 원칙" },

  // 8. special_structures
  { lvl: 4, cat: 'special_structures', form: 1, s: "Scarcely ______ the boardroom when heated arguments broke out among the directors.", a: "had the mediator entered", opts: ["had the mediator entered", "the mediator had entered", "did the mediator enter", "was the mediator entered"], t: "중재자가 이사회 회의실에 들어가자마자 이사들 사이에 격렬한 언쟁이 터져 나왔다.", f: ["'Scarcely had S p.p. when ...' 구문이므로 문두 Scarcely에 의해 도치된 had the mediator entered가 정답입니다.", "평서문 어순은 Scarcely 도치 위반입니다.", "did enter는 대과거 표현에 부적절합니다.", "수동태는 중재자가 입력된 것이 되어 비문입니다."], cp: "Scarcely had + S + p.p. ... when + 과거동사", nu: "즉각적 발생을 나타내는 Scarcely ... when 대과거 도치 구문" },
  { lvl: 4, cat: 'special_structures', form: 1, s: "Under no circumstances ______ confidential client data be disclosed to unauthorized third parties.", a: "may", opts: ["may", "it may", "can it", "that may"], t: "어떠한 상황에서도 기밀 고객 데이터가 무권한 제3자에게 공개되어서는 결코 안 된다.", f: ["부정어구 'Under no circumstances'가 문두에 강조되어 조동사와 주어가 도치되므로 may가 정답입니다.", "평서문 it may는 부정어구 도치 위반입니다.", "can it은 data와 대명사 it이 중복되어 비문입니다.", "that은 불필요합니다."], cp: "Under no circumstances + 조동사(may) + 주어 + be p.p.", nu: "강한 금지를 나타내는 부정 전치사구 문두 배치에 따른 조동사 도치" },
  { lvl: 4, cat: 'special_structures', form: 1, s: "Little ______ that the covert operation had already been compromised by foreign intelligence.", a: "did the agents suspect", opts: ["did the agents suspect", "the agents suspected", "had the agents suspected", "were the agents suspected"], t: "요원들은 그 비밀 작전이 이미 외국 정보기관에 의해 노출되었다는 것을 전혀 의심하지 못했다.", f: ["부정어 Little이 문두에 오고 일반동사 suspect를 도치시키므로 [did + 주어 + 동사원형]인 did the agents suspect가 정답입니다.", "평서문 어순은 Little 도치 위반입니다.", "had suspected는 과거완료 도치로 주절 시점에 부적절합니다.", "수동태는 요원들이 의심받은 것이 되어 비문입니다."], cp: "Little + did + 주어 + 동사원형(suspect) + that절", nu: "부정 부사 Little의 문두 도치와 일반동사의 do/did 도치 공식" },
  { lvl: 4, cat: 'special_structures', form: 1, s: "Only after extensive peer review ______ the revolutionary scientific paper published.", a: "was", opts: ["was", "did", "has", "it was"], t: "광범위한 동료 평가를 거친 후에야 비로소 그 혁명적인 과학 논문이 발표되었다.", f: ["'Only + 전치사구'가 문두에 오고 수동태(be published)이므로 단수 be동사 was가 정답입니다.", "did 뒤에는 동사원형이 와야 하므로 과거분사 published 앞에 불가합니다.", "과거 역사적 사실에 현재완료는 모순입니다.", "평서문 어순 it was는 도치 위반입니다."], cp: "Only after 부사구 + was + 주어 + p.p.(published)", nu: "Only 부사구 문두 강조에 따른 수동태 be동사의 선행 도치" },

  // 9. verb_patterns
  { lvl: 4, cat: 'verb_patterns', form: 1, s: "The injured hiker had to ______ motionless in the ravine until the rescue helicopter arrived.", a: "lie", opts: ["lie", "lay", "laid", "lying"], t: "부상당한 등산객은 구조 헬리콥터가 도착할 때까지 협곡에서 꼼짝없이 누워 있어야만 했다.", f: ["'눕다'라는 뜻의 자동사 원형이 had to 뒤에 와야 하므로 lie가 정답입니다.", "lay는 타동사 원형 또는 lie의 과거형으로 to 뒤에 올 수 없습니다.", "laid는 타동사 lay의 과거/과거분사형입니다.", "had to 뒤에 -ing는 불가합니다."], cp: "had to + 자동사(lie) + motionless", nu: "혼동 동사 lie(눕다-자동사) vs lay(놓다-타동사)의 원형 구별" },
  { lvl: 4, cat: 'verb_patterns', form: 3, s: "The central bank decided to ______ the benchmark interest rate to curb inflationary pressure.", a: "raise", opts: ["raise", "rise", "arise", "rising"], t: "중앙은행은 인플레이션 압력을 억제하기 위해 기준금리를 인상하기로 결정했다.", f: ["목적어(the benchmark interest rate)를 취하는 타동사이자 to 뒤 원형이므로 raise가 정답입니다.", "rise는 자동사로 목적어를 취할 수 없습니다.", "arise는 '발생하다'라는 자동사입니다.", "to 뒤에 -ing는 부적절합니다."], cp: "to + 타동사(raise) + 목적어(interest rate)", nu: "타동사 raise(올리다) vs 자동사 rise(오르다) / arise(발생하다)의 구별" },
  { lvl: 4, cat: 'verb_patterns', form: 3, s: "The newly elected senator firmly declined to ______ upon the ongoing judicial investigation.", a: "comment", opts: ["comment", "mention", "discuss", "explain"], t: "새로 선출된 상원의원은 진행 중인 사법 수사에 대해 언급하기를 단호히 거부했다.", f: ["전치사 upon(=on)과 결합하여 '~에 대해 논평/언급하다'를 이루는 자동사는 comment이므로 comment가 정답입니다.", "mention은 완전타동사로 전치사 upon을 취하지 않습니다.", "discuss는 타동사로 전치사 없이 목적어를 바로 취합니다.", "explain은 타동사입니다."], cp: "comment upon/on + 목적어 ('~에 대해 논평하다')", nu: "전치사 upon과 호응하는 자동사 comment vs 타동사 mention/discuss" },
  { lvl: 4, cat: 'verb_patterns', form: 3, s: "The legal treaty ______ the territorial sovereignty of the disputed island.", a: "asserts", opts: ["asserts", "asserts to", "claims to", "insists on"], t: "그 법적 조약은 분쟁 섬의 영토 주권을 단호히 주장한다(명시한다).", f: ["목적어(the sovereignty)를 직접 취하는 완전타동사이므로 asserts가 정답입니다.", "assert 뒤에 to는 불필요한 전치사입니다.", "claim to 뒤에는 동사원형이 주로 옵니다.", "insist on 뒤에 명사가 오지만 조약이 주어일 때는 assert가 자연스럽습니다."], cp: "타동사(assert) + 목적어(sovereignty)", nu: "외교 및 조약 문서에서 직접 목적어를 취하는 완전타동사 assert" },

  // 10. parallel_agreement
  { lvl: 4, cat: 'parallel_agreement', form: 3, s: "The revolutionary paradigm shift entails not merely altering methodologies but ______ foundational assumptions.", a: "reconceptualizing", opts: ["reconceptualizing", "to reconceptualize", "reconceptualize", "reconceptualized"], t: "그 혁명적인 패러다임 전환은 방법론을 바꾸는 것뿐만 아니라 근본적인 가정을 재개념화하는 것을 수반한다.", f: ["'not merely A(-ing) but B(-ing)'에서 동명사 altering과 대등한 형태를 이루어야 하므로 reconceptualizing이 정답입니다.", "to부정사는 동명사와 병렬을 이루지 못합니다.", "동사원형은 동명사 목적어와 병렬 불가입니다.", "과거분사는 능동 목적어를 취하는 동명사 자리에 부적절합니다."], cp: "not merely A(-ing) but B(-ing)", nu: "상관구문 not merely A but B에서 동명사 목적어 간의 정교한 병렬 구조" },
  { lvl: 4, cat: 'parallel_agreement', form: 3, s: "The executive was recognized for both streamlining supply chain logistics and ______ corporate overhead.", a: "curtailing", opts: ["curtailing", "curtail", "to curtail", "curtailed"], t: "그 임원은 공급망 물류를 간소화한 것과 기업 간접비를 절감한 것 둘 다에 대해 인정받았다.", f: ["전치사 for의 목적어로 동명사 streamlining과 and로 연결되므로 동명사 curtailing이 정답입니다.", "원형 curtail은 streamlining과 병렬 불가입니다.", "to부정사는 for 뒤에 올 수 없습니다.", "과거분사는 능동 목적어를 취하는 동명사와 병렬 불가입니다."], cp: "both A(-ing) and B(-ing)", nu: "전치사 for 뒤에서 이어지는 전문 경영 어휘 동명사 병렬 일치" },
  { lvl: 4, cat: 'parallel_agreement', form: 2, s: "The structural vulnerabilities of ancient aqueducts were vastly different from ______ of modern plumbing.", a: "those", opts: ["those", "that", "it", "them"], t: "고대 수로들의 구조적 취약점들은 현대 배관 시설의 취약점들과는 크게 달랐다.", f: ["비교 대상인 복수명사(The structural vulnerabilities)를 대신 가리키므로 복수 대명사 those가 정답입니다.", "that은 단수명사를 대신합니다.", "it은 한정 수식어를 동반하지 못합니다.", "them은 비교 대명사 those of 구문에 쓸 수 없습니다."], cp: "복수 비교 대상(The vulnerabilities) ➔ those of ...", nu: "비교 구문에서 복수 명사를 대신하는 대명사 those of의 정확한 일치" },
  { lvl: 4, cat: 'parallel_agreement', form: 3, s: "The legal charter mandates neither the arbitrary seizure of assets ______ the warrantless detention of citizens.", a: "nor", opts: ["nor", "or", "and", "but also"], t: "그 법적 헌장은 자산의 임의적 압류도 시민들의 영장 없는 구금도 결코 허용(명령)하지 않는다.", f: ["상관접속사 neither는 nor와 호응하여 양자 부정을 나타내므로 nor가 정답입니다.", "or는 either와 호응합니다.", "and는 both와 호응합니다.", "but also는 not only와 호응합니다."], cp: "neither A nor B (상관접속사 호응)", nu: "헌법 및 법률 조항에서 양자 부정을 규정하는 neither A nor B의 호응" }
];

async function main() {
  console.log('🔑 Authenticating anonymously with Firebase Auth...');
  await signInAnonymously(auth);
  console.log('✅ Authenticated successfully!');

  console.log('🧹 Purging all old questions from Firestore...');
  const oldSnap = await getDocs(collection(db, 'questions'));
  console.log(`Found ${oldSnap.size} old questions.`);

  const docsToDelete = oldSnap.docs;
  while (docsToDelete.length > 0) {
    const chunk = docsToDelete.splice(0, 400);
    const batch = writeBatch(db);
    chunk.forEach(d => batch.delete(d.ref));
    await batch.commit();
    console.log(`Deleted ${chunk.length} old questions...`);
  }
  console.log('✅ Old questions deleted.');

  // Clear cycle challenges cache
  const cycleSnap = await getDocs(collection(db, 'cycle_challenges'));
  if (!cycleSnap.empty) {
    const batch = writeBatch(db);
    cycleSnap.forEach(d => batch.delete(d.ref));
    await batch.commit();
    console.log(`Deleted ${cycleSnap.size} cycle challenge caches.`);
  }

  console.log(`\n🚀 Seeding ${FULL_160_DATA.length} pristine questions (40 per level) into Firestore...`);
  
  // Write in batches of 100
  const allItems = [...FULL_160_DATA];
  let seededCount = 0;
  
  while (allItems.length > 0) {
    const chunk = allItems.splice(0, 80);
    const batch = writeBatch(db);
    const qCol = collection(db, 'questions');

    for (const item of chunk) {
      const catMeta = CATEGORIES[item.cat] || CATEGORIES.subject_verb_agreement;
      const ref = doc(qCol);
      const options = item.opts.map((optText, idx) => ({
        text: optText,
        is_correct: idx === 0,
        feedback: item.f[idx] || (idx === 0 ? '정답입니다!' : '오답입니다.')
      }));

      batch.set(ref, {
        difficulty: `Level ${item.lvl}`,
        level: `Level ${item.lvl}`,
        form: item.form,
        grammarCategory: catMeta.id,
        grammarTag: catMeta.badgeKo,
        sentence: item.s,
        options: options.sort(() => Math.random() - 0.5),
        answer: item.a,
        translation: item.t,
        explanation: {
          chunk_pattern: item.cp,
          nuance: item.nu
        },
        createdAt: serverTimestamp()
      });
      seededCount++;
    }
    await batch.commit();
    console.log(`Committed chunk (${seededCount}/${FULL_160_DATA.length})...`);
  }

  console.log(`\n🎉 Successfully seeded all ${seededCount} questions!`);

  const verifySnap = await getDocs(collection(db, 'questions'));
  console.log(`📊 Firestore total verified questions count: ${verifySnap.size}`);

  const distribution = {};
  verifySnap.forEach(d => {
    const data = d.data();
    const lvl = data.difficulty || 'unknown';
    const cat = data.grammarCategory || 'unknown';
    distribution[lvl] = distribution[lvl] || {};
    distribution[lvl][cat] = (distribution[lvl][cat] || 0) + 1;
  });

  console.log('\n📊 Detailed Category Distribution:');
  console.log(JSON.stringify(distribution, null, 2));
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
